// Generated by tools/slice_floors.py. Where the middle of each floor top sits in its sprite.
export const FLOOR_FY: Record<string, number> = {
  "floor_pink_tile": 0.43,
  "floor_cafe_checker": 0.426,
  "floor_rug_blue": 0.43,
  "floor_rug_pink": 0.43,
  "floor_rug_yellow": 0.446,
  "floor_grass_flowers": 0.432,
  "floor_stone_path": 0.423,
  "floor_wood_plank": 0.455,
  "floor_cream_stone": 0.449,
  "floor_mosaic": 0.447,
  "floor_terracotta": 0.455,
  "floor_wood_light": 0.49,
  "floor_wood_mid": 0.49,
  "floor_wood_dark": 0.49,
  "floor_tatami": 0.49,
  "floor_carpet_plush": 0.49
};
