// Generated by tools/slice_npcs.py. Do not edit by hand.
export const NPC_STRIPS = {
  "npc_elder_w": {
    "frames": 4,
    "fw": 52,
    "fh": 104
  },
  "npc_elder_s": {
    "frames": 4,
    "fw": 52,
    "fh": 104
  },
  "npc_photo_s": {
    "frames": 4,
    "fw": 48,
    "fh": 116
  },
  "npc_photo_s2": {
    "frames": 4,
    "fw": 48,
    "fh": 116
  },
  "npc_photo_e": {
    "frames": 4,
    "fw": 48,
    "fh": 116
  },
  "npc_hiker_e": {
    "frames": 4,
    "fw": 52,
    "fh": 115
  },
  "npc_hiker_s": {
    "frames": 4,
    "fw": 52,
    "fh": 115
  },
  "npc_hiker_w": {
    "frames": 4,
    "fw": 52,
    "fh": 115
  },
  "npc_sunhat_e": {
    "frames": 4,
    "fw": 55,
    "fh": 107
  },
  "npc_sunhat_s": {
    "frames": 4,
    "fw": 55,
    "fh": 107
  },
  "npc_courier_e": {
    "frames": 6,
    "fw": 70,
    "fh": 118
  }
} as const;
