// Generated by tools/slice_floors.py. Do not edit by hand.
export const FLOOR_SPRITES = [
  {
    "key": "floor_pink_tile",
    "file": "floor_pink_tile.png",
    "w": 132,
    "h": 93,
    "dw": 66
  },
  {
    "key": "floor_cafe_checker",
    "file": "floor_cafe_checker.png",
    "w": 132,
    "h": 94,
    "dw": 66
  },
  {
    "key": "floor_rug_blue",
    "file": "floor_rug_blue.png",
    "w": 132,
    "h": 93,
    "dw": 66
  },
  {
    "key": "floor_rug_pink",
    "file": "floor_rug_pink.png",
    "w": 132,
    "h": 93,
    "dw": 66
  },
  {
    "key": "floor_rug_yellow",
    "file": "floor_rug_yellow.png",
    "w": 132,
    "h": 92,
    "dw": 66
  },
  {
    "key": "floor_grass_flowers",
    "file": "floor_grass_flowers.png",
    "w": 132,
    "h": 95,
    "dw": 66
  },
  {
    "key": "floor_stone_path",
    "file": "floor_stone_path.png",
    "w": 132,
    "h": 97,
    "dw": 66
  },
  {
    "key": "floor_wood_plank",
    "file": "floor_wood_plank.png",
    "w": 132,
    "h": 77,
    "dw": 66
  },
  {
    "key": "floor_cream_stone",
    "file": "floor_cream_stone.png",
    "w": 132,
    "h": 78,
    "dw": 66
  },
  {
    "key": "floor_mosaic",
    "file": "floor_mosaic.png",
    "w": 132,
    "h": 76,
    "dw": 66
  },
  {
    "key": "floor_terracotta",
    "file": "floor_terracotta.png",
    "w": 132,
    "h": 77,
    "dw": 66
  },
  {
    "key": "floor_wood_light",
    "file": "floor_wood_light.png",
    "w": 132,
    "h": 100,
    "dw": 66
  },
  {
    "key": "floor_wood_mid",
    "file": "floor_wood_mid.png",
    "w": 132,
    "h": 100,
    "dw": 66
  },
  {
    "key": "floor_wood_dark",
    "file": "floor_wood_dark.png",
    "w": 132,
    "h": 100,
    "dw": 66
  },
  {
    "key": "floor_tatami",
    "file": "floor_tatami.png",
    "w": 132,
    "h": 100,
    "dw": 66
  },
  {
    "key": "floor_carpet_plush",
    "file": "floor_carpet_plush.png",
    "w": 132,
    "h": 100,
    "dw": 66
  }
] as const;
