// Generated by tools/slice_env.py. Do not edit by hand.
export const ENV_SPRITES = [
  {
    "key": "env_ground_spring",
    "file": "env_ground_spring.png",
    "w": 256,
    "h": 256,
    "dw": 128
  },
  {
    "key": "env_ground_summer",
    "file": "env_ground_summer.png",
    "w": 256,
    "h": 256,
    "dw": 128
  },
  {
    "key": "env_ground_autumn",
    "file": "env_ground_autumn.png",
    "w": 256,
    "h": 256,
    "dw": 128
  },
  {
    "key": "env_ground_winter",
    "file": "env_ground_winter.png",
    "w": 256,
    "h": 256,
    "dw": 128
  },
  {
    "key": "env_ground_dirt",
    "file": "env_ground_dirt.png",
    "w": 256,
    "h": 256,
    "dw": 128
  },
  {
    "key": "env_sand",
    "file": "env_sand.png",
    "w": 237,
    "h": 131,
    "dw": 118
  },
  {
    "key": "env_water_spring",
    "file": "env_water_spring.png",
    "w": 188,
    "h": 188,
    "dw": 94
  },
  {
    "key": "env_water_summer",
    "file": "env_water_summer.png",
    "w": 188,
    "h": 188,
    "dw": 94
  },
  {
    "key": "env_water_autumn",
    "file": "env_water_autumn.png",
    "w": 188,
    "h": 188,
    "dw": 94
  },
  {
    "key": "env_water_winter",
    "file": "env_water_winter.png",
    "w": 188,
    "h": 188,
    "dw": 94
  }
] as const;
