// Generated by tools/slice_minigames.py. Do not edit by hand.
export const MG_SPRITES = [
  {
    "key": "mg_bg_cafe_day",
    "file": "mg_bg_cafe_day.jpg",
    "w": 240,
    "h": 124,
    "dw": 480
  },
  {
    "key": "mg_bg_cafe_sunset",
    "file": "mg_bg_cafe_sunset.jpg",
    "w": 241,
    "h": 124,
    "dw": 480
  },
  {
    "key": "mg_ing_matcha",
    "file": "mg_ing_matcha.png",
    "w": 48,
    "h": 61,
    "dw": 40
  },
  {
    "key": "mg_ing_milk",
    "file": "mg_ing_milk.png",
    "w": 43,
    "h": 64,
    "dw": 40
  },
  {
    "key": "mg_ing_oatmilk",
    "file": "mg_ing_oatmilk.png",
    "w": 45,
    "h": 64,
    "dw": 40
  },
  {
    "key": "mg_ing_ice",
    "file": "mg_ing_ice.png",
    "w": 51,
    "h": 62,
    "dw": 40
  },
  {
    "key": "mg_ing_strawberry",
    "file": "mg_ing_strawberry.png",
    "w": 51,
    "h": 62,
    "dw": 40
  },
  {
    "key": "mg_ing_syrup",
    "file": "mg_ing_syrup.png",
    "w": 40,
    "h": 71,
    "dw": 40
  },
  {
    "key": "mg_ing_boba",
    "file": "mg_ing_boba.png",
    "w": 47,
    "h": 61,
    "dw": 40
  },
  {
    "key": "mg_ing_cream",
    "file": "mg_ing_cream.png",
    "w": 51,
    "h": 64,
    "dw": 40
  },
  {
    "key": "mg_ing_cocoa",
    "file": "mg_ing_cocoa.png",
    "w": 50,
    "h": 62,
    "dw": 40
  },
  {
    "key": "mg_ing_blossom",
    "file": "mg_ing_blossom.png",
    "w": 51,
    "h": 62,
    "dw": 40
  },
  {
    "key": "mg_ing_cinnamon",
    "file": "mg_ing_cinnamon.png",
    "w": 48,
    "h": 63,
    "dw": 40
  },
  {
    "key": "mg_ing_vanilla",
    "file": "mg_ing_vanilla.png",
    "w": 55,
    "h": 63,
    "dw": 40
  },
  {
    "key": "mg_cup_1",
    "file": "mg_cup_1.png",
    "w": 69,
    "h": 58,
    "dw": 56
  },
  {
    "key": "mg_cup_2",
    "file": "mg_cup_2.png",
    "w": 69,
    "h": 62,
    "dw": 56
  },
  {
    "key": "mg_cup_3",
    "file": "mg_cup_3.png",
    "w": 68,
    "h": 58,
    "dw": 56
  },
  {
    "key": "mg_cup_4",
    "file": "mg_cup_4.png",
    "w": 68,
    "h": 61,
    "dw": 56
  },
  {
    "key": "mg_cup_5",
    "file": "mg_cup_5.png",
    "w": 68,
    "h": 58,
    "dw": 56
  },
  {
    "key": "mg_cup_6",
    "file": "mg_cup_6.png",
    "w": 68,
    "h": 62,
    "dw": 56
  },
  {
    "key": "mg_cup_7",
    "file": "mg_cup_7.png",
    "w": 69,
    "h": 58,
    "dw": 56
  },
  {
    "key": "mg_cup_8",
    "file": "mg_cup_8.png",
    "w": 69,
    "h": 62,
    "dw": 56
  },
  {
    "key": "mg_tray",
    "file": "mg_tray.png",
    "w": 135,
    "h": 109,
    "dw": 100
  },
  {
    "key": "mg_stencil_heart",
    "file": "mg_stencil_heart.png",
    "w": 39,
    "h": 32,
    "dw": 30
  },
  {
    "key": "mg_stencil_star",
    "file": "mg_stencil_star.png",
    "w": 39,
    "h": 35,
    "dw": 30
  },
  {
    "key": "mg_stencil_cat",
    "file": "mg_stencil_cat.png",
    "w": 40,
    "h": 35,
    "dw": 30
  },
  {
    "key": "mg_stencil_leaf",
    "file": "mg_stencil_leaf.png",
    "w": 35,
    "h": 39,
    "dw": 30
  },
  {
    "key": "mg_stencil_flower",
    "file": "mg_stencil_flower.png",
    "w": 39,
    "h": 38,
    "dw": 30
  },
  {
    "key": "mg_cust_1",
    "file": "mg_cust_1.png",
    "w": 44,
    "h": 71,
    "dw": 36
  },
  {
    "key": "mg_cust_2",
    "file": "mg_cust_2.png",
    "w": 40,
    "h": 69,
    "dw": 36
  },
  {
    "key": "mg_cust_3",
    "file": "mg_cust_3.png",
    "w": 42,
    "h": 68,
    "dw": 36
  },
  {
    "key": "mg_cust_4",
    "file": "mg_cust_4.png",
    "w": 42,
    "h": 69,
    "dw": 36
  },
  {
    "key": "mg_cust_5",
    "file": "mg_cust_5.png",
    "w": 42,
    "h": 68,
    "dw": 36
  },
  {
    "key": "mg_cust_6",
    "file": "mg_cust_6.png",
    "w": 42,
    "h": 61,
    "dw": 36
  },
  {
    "key": "mg_stars",
    "file": "mg_stars.png",
    "w": 78,
    "h": 51,
    "dw": 90
  },
  {
    "key": "mg_tipjar",
    "file": "mg_tipjar.png",
    "w": 51,
    "h": 65,
    "dw": 44
  },
  {
    "key": "mg_rush_badge",
    "file": "mg_rush_badge.png",
    "w": 43,
    "h": 44,
    "dw": 36
  },
  {
    "key": "mg_book_cover",
    "file": "mg_book_cover.png",
    "w": 65,
    "h": 80,
    "dw": 56
  },
  {
    "key": "mg_counter",
    "file": "mg_counter.png",
    "w": 223,
    "h": 101,
    "dw": 190
  },
  {
    "key": "mg_order_window",
    "file": "mg_order_window.png",
    "w": 98,
    "h": 104,
    "dw": 84
  },
  {
    "key": "mg_prep",
    "file": "mg_prep.png",
    "w": 135,
    "h": 118,
    "dw": 110
  },
  {
    "key": "mg_whisk",
    "file": "mg_whisk.png",
    "w": 50,
    "h": 97,
    "dw": 40
  },
  {
    "key": "mg_bowl",
    "file": "mg_bowl.png",
    "w": 54,
    "h": 46,
    "dw": 46
  },
  {
    "key": "mg_sky_day",
    "file": "mg_sky_day.jpg",
    "w": 257,
    "h": 82,
    "dw": 480
  },
  {
    "key": "mg_sky_golden",
    "file": "mg_sky_golden.jpg",
    "w": 258,
    "h": 82,
    "dw": 480
  },
  {
    "key": "mg_sky_night",
    "file": "mg_sky_night.jpg",
    "w": 257,
    "h": 82,
    "dw": 480
  },
  {
    "key": "mg_fish_guppy",
    "file": "mg_fish_guppy.png",
    "w": 68,
    "h": 34,
    "dw": 34
  },
  {
    "key": "mg_fish_tang",
    "file": "mg_fish_tang.png",
    "w": 68,
    "h": 42,
    "dw": 34
  },
  {
    "key": "mg_fish_bunny",
    "file": "mg_fish_bunny.png",
    "w": 68,
    "h": 39,
    "dw": 34
  },
  {
    "key": "mg_fish_bass",
    "file": "mg_fish_bass.png",
    "w": 68,
    "h": 33,
    "dw": 34
  },
  {
    "key": "mg_fish_guppy_glow",
    "file": "mg_fish_guppy_glow.png",
    "w": 67,
    "h": 35,
    "dw": 36
  },
  {
    "key": "mg_fish_tang_glow",
    "file": "mg_fish_tang_glow.png",
    "w": 71,
    "h": 42,
    "dw": 36
  },
  {
    "key": "mg_fish_bass_glow",
    "file": "mg_fish_bass_glow.png",
    "w": 72,
    "h": 34,
    "dw": 36
  },
  {
    "key": "mg_crate",
    "file": "mg_crate.png",
    "w": 80,
    "h": 75,
    "dw": 40
  },
  {
    "key": "mg_crate_open",
    "file": "mg_crate_open.png",
    "w": 108,
    "h": 81,
    "dw": 54
  },
  {
    "key": "mg_bobber",
    "file": "mg_bobber.png",
    "w": 27,
    "h": 69,
    "dw": 14
  },
  {
    "key": "mg_hook",
    "file": "mg_hook.png",
    "w": 28,
    "h": 49,
    "dw": 14
  },
  {
    "key": "mg_ring",
    "file": "mg_ring.png",
    "w": 102,
    "h": 59,
    "dw": 70
  },
  {
    "key": "mg_jelly_peach",
    "file": "mg_jelly_peach.png",
    "w": 49,
    "h": 62,
    "dw": 28
  },
  {
    "key": "mg_jelly_mint",
    "file": "mg_jelly_mint.png",
    "w": 46,
    "h": 71,
    "dw": 26
  },
  {
    "key": "mg_octopus",
    "file": "mg_octopus.png",
    "w": 61,
    "h": 81,
    "dw": 34
  },
  {
    "key": "mg_starfish",
    "file": "mg_starfish.png",
    "w": 41,
    "h": 42,
    "dw": 26
  },
  {
    "key": "mg_bottle",
    "file": "mg_bottle.png",
    "w": 70,
    "h": 112,
    "dw": 36
  },
  {
    "key": "mg_journal",
    "file": "mg_journal.png",
    "w": 110,
    "h": 132,
    "dw": 70
  },
  {
    "key": "mg_tank",
    "file": "mg_tank.png",
    "w": 183,
    "h": 123,
    "dw": 110
  },
  {
    "key": "mg_arcade_front",
    "file": "mg_arcade_front.png",
    "w": 240,
    "h": 187,
    "dw": 120
  },
  {
    "key": "mg_cabinet",
    "file": "mg_cabinet.png",
    "w": 168,
    "h": 200,
    "dw": 90
  },
  {
    "key": "mg_claw_open",
    "file": "mg_claw_open.png",
    "w": 51,
    "h": 67,
    "dw": 34
  },
  {
    "key": "mg_claw_closing",
    "file": "mg_claw_closing.png",
    "w": 50,
    "h": 67,
    "dw": 34
  },
  {
    "key": "mg_claw_closed",
    "file": "mg_claw_closed.png",
    "w": 41,
    "h": 68,
    "dw": 34
  },
  {
    "key": "mg_claw_lift",
    "file": "mg_claw_lift.png",
    "w": 42,
    "h": 80,
    "dw": 34
  },
  {
    "key": "mg_rail",
    "file": "mg_rail.png",
    "w": 146,
    "h": 32,
    "dw": 120
  },
  {
    "key": "mg_cable",
    "file": "mg_cable.png",
    "w": 19,
    "h": 55,
    "dw": 12
  },
  {
    "key": "mg_box_pink",
    "file": "mg_box_pink.png",
    "w": 65,
    "h": 63,
    "dw": 40
  },
  {
    "key": "mg_box_green",
    "file": "mg_box_green.png",
    "w": 66,
    "h": 63,
    "dw": 40
  },
  {
    "key": "mg_box_blue",
    "file": "mg_box_blue.png",
    "w": 67,
    "h": 63,
    "dw": 40
  },
  {
    "key": "mg_heavy_pink",
    "file": "mg_heavy_pink.png",
    "w": 71,
    "h": 94,
    "dw": 46
  },
  {
    "key": "mg_heavy_green",
    "file": "mg_heavy_green.png",
    "w": 72,
    "h": 94,
    "dw": 46
  },
  {
    "key": "mg_heavy_blue",
    "file": "mg_heavy_blue.png",
    "w": 73,
    "h": 94,
    "dw": 46
  },
  {
    "key": "mg_token_heart",
    "file": "mg_token_heart.png",
    "w": 49,
    "h": 49,
    "dw": 26
  },
  {
    "key": "mg_token_star",
    "file": "mg_token_star.png",
    "w": 50,
    "h": 49,
    "dw": 26
  },
  {
    "key": "mg_token_silver",
    "file": "mg_token_silver.png",
    "w": 49,
    "h": 49,
    "dw": 26
  },
  {
    "key": "mg_token_gold",
    "file": "mg_token_gold.png",
    "w": 50,
    "h": 49,
    "dw": 26
  }
] as const;
