// Generated by tools/slice_sprites.py. Do not edit by hand.
export const SPRITES = [
  {
    "key": "floor_wood",
    "file": "floor_wood.png",
    "w": 132,
    "h": 86,
    "dw": 66
  },
  {
    "key": "wall_single",
    "file": "wall_single.png",
    "w": 72,
    "h": 124,
    "dw": 36
  },
  {
    "key": "wall_corner",
    "file": "wall_corner.png",
    "w": 120,
    "h": 128,
    "dw": 60
  },
  {
    "key": "wall_window",
    "file": "wall_window.png",
    "w": 86,
    "h": 129,
    "dw": 43
  },
  {
    "key": "wall_door",
    "file": "wall_door.png",
    "w": 76,
    "h": 133,
    "dw": 38
  },
  {
    "key": "bed_gingham",
    "file": "bed_gingham.png",
    "w": 200,
    "h": 176,
    "dw": 100
  },
  {
    "key": "nightstand",
    "file": "nightstand.png",
    "w": 88,
    "h": 116,
    "dw": 44
  },
  {
    "key": "chair_sage",
    "file": "chair_sage.png",
    "w": 80,
    "h": 112,
    "dw": 40
  },
  {
    "key": "mug",
    "file": "mug.png",
    "w": 44,
    "h": 42,
    "dw": 22
  },
  {
    "key": "xmas_tree",
    "file": "xmas_tree.png",
    "w": 88,
    "h": 161,
    "dw": 44
  },
  {
    "key": "blanket_red",
    "file": "blanket_red.png",
    "w": 112,
    "h": 109,
    "dw": 56
  },
  {
    "key": "tree_spring",
    "file": "tree_spring.png",
    "w": 71,
    "h": 97,
    "dw": 38
  },
  {
    "key": "tree_summer",
    "file": "tree_summer.png",
    "w": 72,
    "h": 97,
    "dw": 38
  },
  {
    "key": "tree_autumn",
    "file": "tree_autumn.png",
    "w": 76,
    "h": 93,
    "dw": 38
  },
  {
    "key": "tree_winter",
    "file": "tree_winter.png",
    "w": 72,
    "h": 97,
    "dw": 40
  },
  {
    "key": "blanket_spring",
    "file": "blanket_spring.png",
    "w": 100,
    "h": 80,
    "dw": 50
  },
  {
    "key": "blanket_summer",
    "file": "blanket_summer.png",
    "w": 100,
    "h": 82,
    "dw": 50
  },
  {
    "key": "blanket_autumn",
    "file": "blanket_autumn.png",
    "w": 100,
    "h": 80,
    "dw": 50
  },
  {
    "key": "blanket_winter",
    "file": "blanket_winter.png",
    "w": 97,
    "h": 81,
    "dw": 50
  },
  {
    "key": "cafe_exterior",
    "file": "cafe_exterior.png",
    "w": 240,
    "h": 200,
    "dw": 120
  },
  {
    "key": "wooden_chair_a",
    "file": "wooden_chair_a.png",
    "w": 67,
    "h": 102,
    "dw": 34
  },
  {
    "key": "wooden_chair_b",
    "file": "wooden_chair_b.png",
    "w": 65,
    "h": 102,
    "dw": 34
  },
  {
    "key": "cushion_set",
    "file": "cushion_set.png",
    "w": 175,
    "h": 95,
    "dw": 100
  },
  {
    "key": "round_table_set",
    "file": "round_table_set.png",
    "w": 154,
    "h": 114,
    "dw": 90
  },
  {
    "key": "square_table_set",
    "file": "square_table_set.png",
    "w": 173,
    "h": 109,
    "dw": 100
  },
  {
    "key": "bookshelf_cafe",
    "file": "bookshelf_cafe.png",
    "w": 82,
    "h": 88,
    "dw": 44
  },
  {
    "key": "counter_pastry",
    "file": "counter_pastry.png",
    "w": 215,
    "h": 146,
    "dw": 150
  },
  {
    "key": "food_matcha",
    "file": "food_matcha.png",
    "w": 56,
    "h": 42,
    "dw": 28
  },
  {
    "key": "food_tray",
    "file": "food_tray.png",
    "w": 64,
    "h": 41,
    "dw": 32
  },
  {
    "key": "food_cake_a",
    "file": "food_cake_a.png",
    "w": 56,
    "h": 44,
    "dw": 28
  },
  {
    "key": "food_cake_b",
    "file": "food_cake_b.png",
    "w": 56,
    "h": 40,
    "dw": 28
  },
  {
    "key": "food_slice",
    "file": "food_slice.png",
    "w": 56,
    "h": 44,
    "dw": 28
  },
  {
    "key": "food_croissant",
    "file": "food_croissant.png",
    "w": 60,
    "h": 49,
    "dw": 30
  },
  {
    "key": "food_display",
    "file": "food_display.png",
    "w": 64,
    "h": 48,
    "dw": 32
  },
  {
    "key": "food_macarons",
    "file": "food_macarons.png",
    "w": 60,
    "h": 41,
    "dw": 30
  },
  {
    "key": "food_loaf",
    "file": "food_loaf.png",
    "w": 60,
    "h": 42,
    "dw": 30
  },
  {
    "key": "food_bread",
    "file": "food_bread.png",
    "w": 56,
    "h": 48,
    "dw": 28
  },
  {
    "key": "plant_a",
    "file": "plant_a.png",
    "w": 55,
    "h": 70,
    "dw": 30
  },
  {
    "key": "plant_b",
    "file": "plant_b.png",
    "w": 46,
    "h": 60,
    "dw": 28
  },
  {
    "key": "plant_snake",
    "file": "plant_snake.png",
    "w": 46,
    "h": 77,
    "dw": 26
  },
  {
    "key": "lamp",
    "file": "lamp.png",
    "w": 39,
    "h": 62,
    "dw": 22
  },
  {
    "key": "menu_sign",
    "file": "menu_sign.png",
    "w": 48,
    "h": 67,
    "dw": 24
  },
  {
    "key": "suitcase",
    "file": "suitcase.png",
    "w": 56,
    "h": 52,
    "dw": 28
  },
  {
    "key": "couch_sectional",
    "file": "couch_sectional.png",
    "w": 236,
    "h": 152,
    "dw": 150
  },
  {
    "key": "pastry_case",
    "file": "pastry_case.png",
    "w": 200,
    "h": 187,
    "dw": 100
  },
  {
    "key": "bread_shelf",
    "file": "bread_shelf.png",
    "w": 168,
    "h": 180,
    "dw": 84
  },
  {
    "key": "menu_stand_a",
    "file": "menu_stand_a.png",
    "w": 52,
    "h": 75,
    "dw": 26
  },
  {
    "key": "menu_stand_b",
    "file": "menu_stand_b.png",
    "w": 56,
    "h": 81,
    "dw": 28
  },
  {
    "key": "plush_kitty",
    "file": "plush_kitty.png",
    "w": 68,
    "h": 87,
    "dw": 34
  },
  {
    "key": "plush_miffy",
    "file": "plush_miffy.png",
    "w": 64,
    "h": 105,
    "dw": 32
  },
  {
    "key": "palm_grove",
    "file": "palm_grove.png",
    "w": 191,
    "h": 210,
    "dw": 100
  },
  {
    "key": "lifeguard_stand",
    "file": "lifeguard_stand.png",
    "w": 108,
    "h": 128,
    "dw": 76
  },
  {
    "key": "surfboards",
    "file": "surfboards.png",
    "w": 44,
    "h": 75,
    "dw": 28
  },
  {
    "key": "lighthouse",
    "file": "lighthouse.png",
    "w": 215,
    "h": 257,
    "dw": 130
  },
  {
    "key": "miniso",
    "file": "miniso.png",
    "w": 203,
    "h": 146,
    "dw": 130
  },
  {
    "key": "home_house",
    "file": "home_house.png",
    "w": 198,
    "h": 148,
    "dw": 130
  },
  {
    "key": "cottage",
    "file": "cottage.png",
    "w": 117,
    "h": 131,
    "dw": 80
  },
  {
    "key": "pet_golden",
    "file": "pet_golden.png",
    "w": 92,
    "h": 71,
    "dw": 46
  },
  {
    "key": "pet_corgi",
    "file": "pet_corgi.png",
    "w": 67,
    "h": 83,
    "dw": 34
  },
  {
    "key": "pet_bunny",
    "file": "pet_bunny.png",
    "w": 44,
    "h": 65,
    "dw": 22
  },
  {
    "key": "rachel_front",
    "file": "rachel_front.png",
    "w": 62,
    "h": 114,
    "dw": 31
  },
  {
    "key": "rachel_side",
    "file": "rachel_side.png",
    "w": 58,
    "h": 110,
    "dw": 29
  },
  {
    "key": "rachel_back",
    "file": "rachel_back.png",
    "w": 54,
    "h": 106,
    "dw": 27
  }
] as const;

export const WALK_SHEET = { key: "james_walk", file: "james_walk.png", frameWidth: 68, frameHeight: 114, rows: ["front", "back", "left", "right"] } as const;
