// Generated by tools/slice_sheets41_45.py. Do not edit by hand.
export const EXTRA_SPRITES = [
  {
    "key": "toy_beach_kitty",
    "file": "toy_beach_kitty.png",
    "w": 88,
    "h": 111,
    "dw": 44
  },
  {
    "key": "toy_beach_miffy",
    "file": "toy_beach_miffy.png",
    "w": 88,
    "h": 95,
    "dw": 44
  },
  {
    "key": "toy_beach_snoopy",
    "file": "toy_beach_snoopy.png",
    "w": 88,
    "h": 109,
    "dw": 44
  },
  {
    "key": "toy_barista_kitty",
    "file": "toy_barista_kitty.png",
    "w": 88,
    "h": 97,
    "dw": 44
  },
  {
    "key": "toy_barista_miffy",
    "file": "toy_barista_miffy.png",
    "w": 85,
    "h": 130,
    "dw": 44
  },
  {
    "key": "toy_barista_snoopy",
    "file": "toy_barista_snoopy.png",
    "w": 88,
    "h": 106,
    "dw": 44
  },
  {
    "key": "toy_sleepy_kitty",
    "file": "toy_sleepy_kitty.png",
    "w": 88,
    "h": 122,
    "dw": 44
  },
  {
    "key": "toy_sleepy_miffy",
    "file": "toy_sleepy_miffy.png",
    "w": 88,
    "h": 132,
    "dw": 44
  },
  {
    "key": "toy_sleepy_snoopy",
    "file": "toy_sleepy_snoopy.png",
    "w": 83,
    "h": 98,
    "dw": 44
  },
  {
    "key": "toy_golden_kitty",
    "file": "toy_golden_kitty.png",
    "w": 88,
    "h": 110,
    "dw": 44
  },
  {
    "key": "toy_golden_miffy",
    "file": "toy_golden_miffy.png",
    "w": 67,
    "h": 128,
    "dw": 44
  },
  {
    "key": "toy_golden_snoopy",
    "file": "toy_golden_snoopy.png",
    "w": 77,
    "h": 108,
    "dw": 44
  },
  {
    "key": "cap_beach_closed",
    "file": "cap_beach_closed.png",
    "w": 80,
    "h": 101,
    "dw": 40
  },
  {
    "key": "cap_barista_closed",
    "file": "cap_barista_closed.png",
    "w": 80,
    "h": 103,
    "dw": 40
  },
  {
    "key": "cap_beach_open",
    "file": "cap_beach_open.png",
    "w": 80,
    "h": 100,
    "dw": 40
  },
  {
    "key": "cap_pajama_closed",
    "file": "cap_pajama_closed.png",
    "w": 80,
    "h": 102,
    "dw": 40
  },
  {
    "key": "cap_pajama_open",
    "file": "cap_pajama_open.png",
    "w": 80,
    "h": 105,
    "dw": 40
  },
  {
    "key": "cap_golden_closed",
    "file": "cap_golden_closed.png",
    "w": 80,
    "h": 104,
    "dw": 40
  },
  {
    "key": "cap_golden_open",
    "file": "cap_golden_open.png",
    "w": 80,
    "h": 102,
    "dw": 40
  },
  {
    "key": "toy_secret",
    "file": "toy_secret.png",
    "w": 82,
    "h": 127,
    "dw": 44
  },
  {
    "key": "mech_bookshelf_1",
    "file": "mech_bookshelf_1.png",
    "w": 170,
    "h": 114,
    "dw": 120
  },
  {
    "key": "mech_bookshelf_2",
    "file": "mech_bookshelf_2.png",
    "w": 175,
    "h": 114,
    "dw": 120
  },
  {
    "key": "mech_bookshelf_3",
    "file": "mech_bookshelf_3.png",
    "w": 176,
    "h": 114,
    "dw": 120
  },
  {
    "key": "mech_bookshelf_4",
    "file": "mech_bookshelf_4.png",
    "w": 189,
    "h": 114,
    "dw": 120
  },
  {
    "key": "mech_bookshelf_5",
    "file": "mech_bookshelf_5.png",
    "w": 200,
    "h": 119,
    "dw": 120
  },
  {
    "key": "item_scroll",
    "file": "item_scroll.png",
    "w": 49,
    "h": 52,
    "dw": 30
  },
  {
    "key": "item_letter",
    "file": "item_letter.png",
    "w": 53,
    "h": 40,
    "dw": 32
  },
  {
    "key": "item_bookmark",
    "file": "item_bookmark.png",
    "w": 21,
    "h": 67,
    "dw": 18
  },
  {
    "key": "item_ladder",
    "file": "item_ladder.png",
    "w": 107,
    "h": 94,
    "dw": 60
  },
  {
    "key": "mech_vault_1",
    "file": "mech_vault_1.png",
    "w": 54,
    "h": 56,
    "dw": 40
  },
  {
    "key": "mech_vault_2",
    "file": "mech_vault_2.png",
    "w": 52,
    "h": 61,
    "dw": 40
  },
  {
    "key": "mech_vault_3",
    "file": "mech_vault_3.png",
    "w": 64,
    "h": 62,
    "dw": 44
  },
  {
    "key": "bp_glass_cafe",
    "file": "bp_glass_cafe.png",
    "w": 158,
    "h": 75,
    "dw": 120
  },
  {
    "key": "bp_rooftop",
    "file": "bp_rooftop.png",
    "w": 78,
    "h": 75,
    "dw": 80
  },
  {
    "key": "rooftop_done",
    "file": "rooftop_done.png",
    "w": 114,
    "h": 77,
    "dw": 120
  },
  {
    "key": "bp_island",
    "file": "bp_island.png",
    "w": 77,
    "h": 75,
    "dw": 80
  },
  {
    "key": "scaffold_island",
    "file": "scaffold_island.png",
    "w": 55,
    "h": 76,
    "dw": 64
  },
  {
    "key": "island_ext_done",
    "file": "island_ext_done.png",
    "w": 90,
    "h": 85,
    "dw": 100
  },
  {
    "key": "fx_lantern_1",
    "file": "fx_lantern_1.png",
    "w": 45,
    "h": 64,
    "dw": 32
  },
  {
    "key": "fx_lantern_2",
    "file": "fx_lantern_2.png",
    "w": 45,
    "h": 52,
    "dw": 32
  },
  {
    "key": "fx_lantern_3",
    "file": "fx_lantern_3.png",
    "w": 45,
    "h": 51,
    "dw": 36
  },
  {
    "key": "fx_lantern_4",
    "file": "fx_lantern_4.png",
    "w": 45,
    "h": 51,
    "dw": 32
  },
  {
    "key": "fx_tea_balloon",
    "file": "fx_tea_balloon.png",
    "w": 46,
    "h": 84,
    "dw": 32
  },
  {
    "key": "fx_tea_parachute",
    "file": "fx_tea_parachute.png",
    "w": 52,
    "h": 84,
    "dw": 36
  },
  {
    "key": "fx_tea_ribbon",
    "file": "fx_tea_ribbon.png",
    "w": 65,
    "h": 77,
    "dw": 44
  },
  {
    "key": "fx_tea_land",
    "file": "fx_tea_land.png",
    "w": 81,
    "h": 62,
    "dw": 56
  },
  {
    "key": "prop_bottle_drift",
    "file": "prop_bottle_drift.png",
    "w": 50,
    "h": 56,
    "dw": 40
  },
  {
    "key": "prop_bottle_shore",
    "file": "prop_bottle_shore.png",
    "w": 64,
    "h": 50,
    "dw": 44
  },
  {
    "key": "prop_bottle_open",
    "file": "prop_bottle_open.png",
    "w": 48,
    "h": 58,
    "dw": 40
  },
  {
    "key": "fx_splash",
    "file": "fx_splash.png",
    "w": 69,
    "h": 54,
    "dw": 48
  },
  {
    "key": "bottle_note",
    "file": "bottle_note.png",
    "w": 46,
    "h": 62,
    "dw": 32
  },
  {
    "key": "rolled_note",
    "file": "rolled_note.png",
    "w": 50,
    "h": 56,
    "dw": 36
  },
  {
    "key": "balloons_bundle",
    "file": "balloons_bundle.png",
    "w": 50,
    "h": 86,
    "dw": 36
  },
  {
    "key": "balloon_single",
    "file": "balloon_single.png",
    "w": 31,
    "h": 71,
    "dw": 22
  },
  {
    "key": "ui_quad_health",
    "file": "ui_quad_health.png",
    "w": 30,
    "h": 34,
    "dw": 30
  },
  {
    "key": "ui_quad_career",
    "file": "ui_quad_career.png",
    "w": 29,
    "h": 37,
    "dw": 30
  },
  {
    "key": "ui_quad_learning",
    "file": "ui_quad_learning.png",
    "w": 36,
    "h": 30,
    "dw": 34
  },
  {
    "key": "ui_quad_finance",
    "file": "ui_quad_finance.png",
    "w": 34,
    "h": 35,
    "dw": 34
  },
  {
    "key": "ui_quad_romance",
    "file": "ui_quad_romance.png",
    "w": 35,
    "h": 31,
    "dw": 34
  },
  {
    "key": "ui_quad_social",
    "file": "ui_quad_social.png",
    "w": 34,
    "h": 34,
    "dw": 34
  },
  {
    "key": "ui_quad_environment",
    "file": "ui_quad_environment.png",
    "w": 35,
    "h": 34,
    "dw": 34
  },
  {
    "key": "ui_quad_recreation",
    "file": "ui_quad_recreation.png",
    "w": 34,
    "h": 32,
    "dw": 34
  },
  {
    "key": "glass_cafe_done",
    "file": "glass_cafe_done.png",
    "w": 102,
    "h": 86,
    "dw": 120
  },
  {
    "key": "bunting_rainbow",
    "file": "bunting_rainbow.png",
    "w": 199,
    "h": 45,
    "dw": 200
  },
  {
    "key": "bunting_gold",
    "file": "bunting_gold.png",
    "w": 226,
    "h": 23,
    "dw": 200
  },
  {
    "key": "bunting_teal",
    "file": "bunting_teal.png",
    "w": 219,
    "h": 28,
    "dw": 200
  },
  {
    "key": "prop_campfire",
    "file": "prop_campfire.png",
    "w": 80,
    "h": 92,
    "dw": 64
  },
  {
    "key": "fx_star_1",
    "file": "fx_star_1.png",
    "w": 48,
    "h": 46,
    "dw": 24
  },
  {
    "key": "fx_star_2",
    "file": "fx_star_2.png",
    "w": 48,
    "h": 50,
    "dw": 24
  },
  {
    "key": "fx_star_3",
    "file": "fx_star_3.png",
    "w": 48,
    "h": 41,
    "dw": 24
  },
  {
    "key": "fx_star_4",
    "file": "fx_star_4.png",
    "w": 48,
    "h": 47,
    "dw": 24
  },
  {
    "key": "fx_star_5",
    "file": "fx_star_5.png",
    "w": 48,
    "h": 46,
    "dw": 24
  },
  {
    "key": "fx_star_6",
    "file": "fx_star_6.png",
    "w": 48,
    "h": 46,
    "dw": 24
  },
  {
    "key": "ui_streak_1",
    "file": "ui_streak_1.png",
    "w": 34,
    "h": 48,
    "dw": 26
  },
  {
    "key": "ui_streak_2",
    "file": "ui_streak_2.png",
    "w": 40,
    "h": 55,
    "dw": 32
  },
  {
    "key": "ui_streak_3",
    "file": "ui_streak_3.png",
    "w": 46,
    "h": 75,
    "dw": 38
  },
  {
    "key": "ui_streak_4",
    "file": "ui_streak_4.png",
    "w": 52,
    "h": 76,
    "dw": 44
  },
  {
    "key": "ui_streak_5",
    "file": "ui_streak_5.png",
    "w": 64,
    "h": 93,
    "dw": 50
  },
  {
    "key": "ui_lovemap_card",
    "file": "ui_lovemap_card.png",
    "w": 105,
    "h": 142,
    "dw": 64
  },
  {
    "key": "ui_heart_meter",
    "file": "ui_heart_meter.png",
    "w": 30,
    "h": 136,
    "dw": 18
  },
  {
    "key": "prop_jar_closed",
    "file": "prop_jar_closed.png",
    "w": 46,
    "h": 62,
    "dw": 32
  },
  {
    "key": "prop_jar_open",
    "file": "prop_jar_open.png",
    "w": 46,
    "h": 60,
    "dw": 32
  },
  {
    "key": "prop_jar_full",
    "file": "prop_jar_full.png",
    "w": 46,
    "h": 61,
    "dw": 32
  },
  {
    "key": "fx_jar_pop",
    "file": "fx_jar_pop.png",
    "w": 57,
    "h": 61,
    "dw": 36
  },
  {
    "key": "ui_checkin_card",
    "file": "ui_checkin_card.png",
    "w": 97,
    "h": 112,
    "dw": 64
  },
  {
    "key": "ui_whisper_light",
    "file": "ui_whisper_light.png",
    "w": 112,
    "h": 151,
    "dw": 70
  },
  {
    "key": "ui_whisper_med",
    "file": "ui_whisper_med.png",
    "w": 112,
    "h": 151,
    "dw": 70
  },
  {
    "key": "ui_whisper_deep",
    "file": "ui_whisper_deep.png",
    "w": 112,
    "h": 151,
    "dw": 70
  },
  {
    "key": "ui_scratch_base",
    "file": "ui_scratch_base.png",
    "w": 108,
    "h": 151,
    "dw": 70
  },
  {
    "key": "ui_scratch_erased",
    "file": "ui_scratch_erased.png",
    "w": 107,
    "h": 151,
    "dw": 70
  },
  {
    "key": "ui_reveal_1",
    "file": "ui_reveal_1.png",
    "w": 51,
    "h": 43,
    "dw": 36
  },
  {
    "key": "ui_reveal_2",
    "file": "ui_reveal_2.png",
    "w": 51,
    "h": 43,
    "dw": 36
  },
  {
    "key": "ui_reveal_3",
    "file": "ui_reveal_3.png",
    "w": 51,
    "h": 43,
    "dw": 36
  },
  {
    "key": "ui_reveal_4",
    "file": "ui_reveal_4.png",
    "w": 51,
    "h": 45,
    "dw": 36
  },
  {
    "key": "ui_reveal_5",
    "file": "ui_reveal_5.png",
    "w": 51,
    "h": 45,
    "dw": 36
  },
  {
    "key": "ui_reveal_6",
    "file": "ui_reveal_6.png",
    "w": 51,
    "h": 45,
    "dw": 36
  },
  {
    "key": "ui_reveal_7",
    "file": "ui_reveal_7.png",
    "w": 51,
    "h": 44,
    "dw": 36
  },
  {
    "key": "ui_reveal_8",
    "file": "ui_reveal_8.png",
    "w": 51,
    "h": 44,
    "dw": 36
  },
  {
    "key": "ui_reveal_9",
    "file": "ui_reveal_9.png",
    "w": 51,
    "h": 44,
    "dw": 36
  },
  {
    "key": "ui_bid_wave_1",
    "file": "ui_bid_wave_1.png",
    "w": 72,
    "h": 74,
    "dw": 36
  },
  {
    "key": "ui_bid_wave_2",
    "file": "ui_bid_wave_2.png",
    "w": 72,
    "h": 72,
    "dw": 36
  },
  {
    "key": "ui_bid_wave_3",
    "file": "ui_bid_wave_3.png",
    "w": 72,
    "h": 72,
    "dw": 36
  },
  {
    "key": "ui_bid_wave_4",
    "file": "ui_bid_wave_4.png",
    "w": 72,
    "h": 73,
    "dw": 36
  },
  {
    "key": "ui_bid_tea_1",
    "file": "ui_bid_tea_1.png",
    "w": 72,
    "h": 73,
    "dw": 36
  },
  {
    "key": "ui_bid_tea_2",
    "file": "ui_bid_tea_2.png",
    "w": 72,
    "h": 71,
    "dw": 36
  },
  {
    "key": "ui_bid_tea_3",
    "file": "ui_bid_tea_3.png",
    "w": 72,
    "h": 71,
    "dw": 36
  },
  {
    "key": "ui_bid_tea_4",
    "file": "ui_bid_tea_4.png",
    "w": 72,
    "h": 72,
    "dw": 36
  },
  {
    "key": "ui_bid_flower_1",
    "file": "ui_bid_flower_1.png",
    "w": 72,
    "h": 74,
    "dw": 36
  },
  {
    "key": "ui_bid_flower_2",
    "file": "ui_bid_flower_2.png",
    "w": 72,
    "h": 72,
    "dw": 36
  },
  {
    "key": "ui_bid_flower_3",
    "file": "ui_bid_flower_3.png",
    "w": 72,
    "h": 72,
    "dw": 36
  },
  {
    "key": "ui_bid_flower_4",
    "file": "ui_bid_flower_4.png",
    "w": 72,
    "h": 73,
    "dw": 36
  },
  {
    "key": "prop_kitchen_oven",
    "file": "prop_kitchen_oven.png",
    "w": 63,
    "h": 74,
    "dw": 46
  },
  {
    "key": "prop_kitchen_fridge",
    "file": "prop_kitchen_fridge.png",
    "w": 51,
    "h": 95,
    "dw": 44
  },
  {
    "key": "prop_kitchen_island",
    "file": "prop_kitchen_island.png",
    "w": 110,
    "h": 54,
    "dw": 92
  },
  {
    "key": "prop_kitchen_potrack",
    "file": "prop_kitchen_potrack.png",
    "w": 76,
    "h": 69,
    "dw": 60
  },
  {
    "key": "prop_kitchen_sink",
    "file": "prop_kitchen_sink.png",
    "w": 128,
    "h": 78,
    "dw": 100
  },
  {
    "key": "prop_dining_table",
    "file": "prop_dining_table.png",
    "w": 123,
    "h": 74,
    "dw": 100
  },
  {
    "key": "prop_kitchen_dishes",
    "file": "prop_kitchen_dishes.png",
    "w": 69,
    "h": 65,
    "dw": 38
  },
  {
    "key": "prop_living_cushions",
    "file": "prop_living_cushions.png",
    "w": 124,
    "h": 90,
    "dw": 70
  },
  {
    "key": "prop_living_tv",
    "file": "prop_living_tv.png",
    "w": 109,
    "h": 103,
    "dw": 92
  },
  {
    "key": "prop_living_record",
    "file": "prop_living_record.png",
    "w": 78,
    "h": 70,
    "dw": 50
  },
  {
    "key": "prop_living_piano",
    "file": "prop_living_piano.png",
    "w": 80,
    "h": 76,
    "dw": 84
  },
  {
    "key": "prop_living_desk",
    "file": "prop_living_desk.png",
    "w": 74,
    "h": 68,
    "dw": 62
  },
  {
    "key": "prop_living_easel",
    "file": "prop_living_easel.png",
    "w": 37,
    "h": 79,
    "dw": 36
  },
  {
    "key": "prop_living_yoga",
    "file": "prop_living_yoga.png",
    "w": 57,
    "h": 34,
    "dw": 38
  },
  {
    "key": "prop_bed_wardrobe",
    "file": "prop_bed_wardrobe.png",
    "w": 67,
    "h": 99,
    "dw": 50
  },
  {
    "key": "prop_bed_dresser",
    "file": "prop_bed_dresser.png",
    "w": 72,
    "h": 59,
    "dw": 54
  },
  {
    "key": "prop_bed_vanity",
    "file": "prop_bed_vanity.png",
    "w": 70,
    "h": 96,
    "dw": 54
  },
  {
    "key": "prop_bed_nightlight_a",
    "file": "prop_bed_nightlight_a.png",
    "w": 21,
    "h": 38,
    "dw": 22
  },
  {
    "key": "prop_bed_nightlight_b",
    "file": "prop_bed_nightlight_b.png",
    "w": 25,
    "h": 37,
    "dw": 22
  },
  {
    "key": "prop_bath_tub",
    "file": "prop_bath_tub.png",
    "w": 99,
    "h": 82,
    "dw": 92
  },
  {
    "key": "prop_bath_sink",
    "file": "prop_bath_sink.png",
    "w": 71,
    "h": 80,
    "dw": 56
  },
  {
    "key": "prop_bath_plant_a",
    "file": "prop_bath_plant_a.png",
    "w": 46,
    "h": 76,
    "dw": 46
  },
  {
    "key": "prop_bath_plant_b",
    "file": "prop_bath_plant_b.png",
    "w": 31,
    "h": 37,
    "dw": 26
  },
  {
    "key": "prop_bath_plant_c",
    "file": "prop_bath_plant_c.png",
    "w": 44,
    "h": 84,
    "dw": 40
  },
  {
    "key": "prop_outdoor_hottub",
    "file": "prop_outdoor_hottub.png",
    "w": 98,
    "h": 73,
    "dw": 100
  },
  {
    "key": "prop_outdoor_hammock",
    "file": "prop_outdoor_hammock.png",
    "w": 103,
    "h": 73,
    "dw": 88
  },
  {
    "key": "prop_outdoor_firepit",
    "file": "prop_outdoor_firepit.png",
    "w": 73,
    "h": 65,
    "dw": 54
  },
  {
    "key": "prop_outdoor_bbq",
    "file": "prop_outdoor_bbq.png",
    "w": 52,
    "h": 72,
    "dw": 38
  },
  {
    "key": "prop_outdoor_garden_a",
    "file": "prop_outdoor_garden_a.png",
    "w": 98,
    "h": 61,
    "dw": 88
  },
  {
    "key": "prop_outdoor_garden_b",
    "file": "prop_outdoor_garden_b.png",
    "w": 104,
    "h": 71,
    "dw": 88
  },
  {
    "key": "prop_outdoor_garden_c",
    "file": "prop_outdoor_garden_c.png",
    "w": 105,
    "h": 74,
    "dw": 88
  },
  {
    "key": "prop_outdoor_palm",
    "file": "prop_outdoor_palm.png",
    "w": 54,
    "h": 73,
    "dw": 44
  },
  {
    "key": "prop_outdoor_greenhouse",
    "file": "prop_outdoor_greenhouse.png",
    "w": 115,
    "h": 111,
    "dw": 140
  },
  {
    "key": "prop_outdoor_coop",
    "file": "prop_outdoor_coop.png",
    "w": 82,
    "h": 88,
    "dw": 90
  },
  {
    "key": "prop_outdoor_swing",
    "file": "prop_outdoor_swing.png",
    "w": 122,
    "h": 113,
    "dw": 140
  },
  {
    "key": "prop_outdoor_gazebo",
    "file": "prop_outdoor_gazebo.png",
    "w": 104,
    "h": 116,
    "dw": 150
  },
  {
    "key": "prop_outdoor_pergola",
    "file": "prop_outdoor_pergola.png",
    "w": 126,
    "h": 111,
    "dw": 150
  },
  {
    "key": "prop_wall_print_a",
    "file": "prop_wall_print_a.png",
    "w": 44,
    "h": 51,
    "dw": 40
  },
  {
    "key": "prop_wall_print_b",
    "file": "prop_wall_print_b.png",
    "w": 46,
    "h": 52,
    "dw": 40
  },
  {
    "key": "prop_wall_mirror_round",
    "file": "prop_wall_mirror_round.png",
    "w": 47,
    "h": 47,
    "dw": 34
  },
  {
    "key": "prop_wall_mirror_oval",
    "file": "prop_wall_mirror_oval.png",
    "w": 39,
    "h": 50,
    "dw": 30
  },
  {
    "key": "prop_wall_shelf",
    "file": "prop_wall_shelf.png",
    "w": 37,
    "h": 42,
    "dw": 34
  },
  {
    "key": "prop_wall_neon_cafe",
    "file": "prop_wall_neon_cafe.png",
    "w": 57,
    "h": 56,
    "dw": 50
  },
  {
    "key": "prop_wall_neon_cup",
    "file": "prop_wall_neon_cup.png",
    "w": 56,
    "h": 56,
    "dw": 50
  },
  {
    "key": "prop_wall_neon_coffee",
    "file": "prop_wall_neon_coffee.png",
    "w": 49,
    "h": 23,
    "dw": 50
  },
  {
    "key": "prop_wall_neon_sign",
    "file": "prop_wall_neon_sign.png",
    "w": 56,
    "h": 32,
    "dw": 50
  },
  {
    "key": "prop_wall_bunting",
    "file": "prop_wall_bunting.png",
    "w": 125,
    "h": 37,
    "dw": 70
  },
  {
    "key": "prop_autumn_pumpkin",
    "file": "prop_autumn_pumpkin.png",
    "w": 64,
    "h": 56,
    "dw": 44
  },
  {
    "key": "prop_autumn_rake",
    "file": "prop_autumn_rake.png",
    "w": 50,
    "h": 54,
    "dw": 36
  },
  {
    "key": "prop_autumn_blanket",
    "file": "prop_autumn_blanket.png",
    "w": 58,
    "h": 44,
    "dw": 44
  },
  {
    "key": "prop_autumn_basket",
    "file": "prop_autumn_basket.png",
    "w": 48,
    "h": 50,
    "dw": 40
  },
  {
    "key": "prop_autumn_scarecrow",
    "file": "prop_autumn_scarecrow.png",
    "w": 46,
    "h": 56,
    "dw": 44
  },
  {
    "key": "prop_autumn_wreath",
    "file": "prop_autumn_wreath.png",
    "w": 53,
    "h": 53,
    "dw": 36
  },
  {
    "key": "prop_autumn_candle",
    "file": "prop_autumn_candle.png",
    "w": 36,
    "h": 50,
    "dw": 24
  },
  {
    "key": "prop_spring_wateringcan",
    "file": "prop_spring_wateringcan.png",
    "w": 55,
    "h": 40,
    "dw": 40
  },
  {
    "key": "prop_spring_blossom",
    "file": "prop_spring_blossom.png",
    "w": 53,
    "h": 51,
    "dw": 40
  },
  {
    "key": "prop_spring_seeds",
    "file": "prop_spring_seeds.png",
    "w": 52,
    "h": 42,
    "dw": 38
  },
  {
    "key": "prop_spring_gnome",
    "file": "prop_spring_gnome.png",
    "w": 30,
    "h": 51,
    "dw": 30
  },
  {
    "key": "prop_spring_kite",
    "file": "prop_spring_kite.png",
    "w": 49,
    "h": 51,
    "dw": 40
  },
  {
    "key": "prop_spring_birdfeeder",
    "file": "prop_spring_birdfeeder.png",
    "w": 41,
    "h": 52,
    "dw": 30
  },
  {
    "key": "prop_spring_wreath",
    "file": "prop_spring_wreath.png",
    "w": 52,
    "h": 50,
    "dw": 36
  },
  {
    "key": "prop_summer_palm",
    "file": "prop_summer_palm.png",
    "w": 44,
    "h": 48,
    "dw": 40
  },
  {
    "key": "prop_summer_ball",
    "file": "prop_summer_ball.png",
    "w": 43,
    "h": 43,
    "dw": 34
  },
  {
    "key": "prop_summer_cart",
    "file": "prop_summer_cart.png",
    "w": 53,
    "h": 54,
    "dw": 54
  },
  {
    "key": "prop_summer_surfboards",
    "file": "prop_summer_surfboards.png",
    "w": 55,
    "h": 53,
    "dw": 44
  },
  {
    "key": "prop_summer_shells",
    "file": "prop_summer_shells.png",
    "w": 46,
    "h": 42,
    "dw": 36
  },
  {
    "key": "prop_summer_fan",
    "file": "prop_summer_fan.png",
    "w": 41,
    "h": 51,
    "dw": 36
  },
  {
    "key": "prop_summer_basket",
    "file": "prop_summer_basket.png",
    "w": 51,
    "h": 44,
    "dw": 40
  },
  {
    "key": "prop_summer_hammock",
    "file": "prop_summer_hammock.png",
    "w": 54,
    "h": 47,
    "dw": 50
  },
  {
    "key": "prop_winter_ornament",
    "file": "prop_winter_ornament.png",
    "w": 43,
    "h": 49,
    "dw": 30
  },
  {
    "key": "prop_winter_sled",
    "file": "prop_winter_sled.png",
    "w": 51,
    "h": 48,
    "dw": 44
  },
  {
    "key": "prop_winter_scarf",
    "file": "prop_winter_scarf.png",
    "w": 50,
    "h": 51,
    "dw": 34
  },
  {
    "key": "prop_winter_gingerbread",
    "file": "prop_winter_gingerbread.png",
    "w": 41,
    "h": 48,
    "dw": 30
  },
  {
    "key": "prop_winter_mistletoe",
    "file": "prop_winter_mistletoe.png",
    "w": 45,
    "h": 52,
    "dw": 32
  },
  {
    "key": "prop_winter_boots",
    "file": "prop_winter_boots.png",
    "w": 47,
    "h": 49,
    "dw": 36
  },
  {
    "key": "prop_winter_cocoa",
    "file": "prop_winter_cocoa.png",
    "w": 41,
    "h": 36,
    "dw": 30
  },
  {
    "key": "prop_winter_bauble",
    "file": "prop_winter_bauble.png",
    "w": 34,
    "h": 50,
    "dw": 30
  },
  {
    "key": "prop_pet_bed_a",
    "file": "prop_pet_bed_a.png",
    "w": 75,
    "h": 50,
    "dw": 56
  },
  {
    "key": "prop_pet_bed_b",
    "file": "prop_pet_bed_b.png",
    "w": 72,
    "h": 39,
    "dw": 56
  },
  {
    "key": "prop_pet_bed_c",
    "file": "prop_pet_bed_c.png",
    "w": 74,
    "h": 36,
    "dw": 56
  },
  {
    "key": "prop_pet_bowls",
    "file": "prop_pet_bowls.png",
    "w": 83,
    "h": 47,
    "dw": 50
  },
  {
    "key": "prop_pet_toy",
    "file": "prop_pet_toy.png",
    "w": 74,
    "h": 49,
    "dw": 40
  },
  {
    "key": "prop_cafe_espresso",
    "file": "prop_cafe_espresso.png",
    "w": 80,
    "h": 57,
    "dw": 60
  },
  {
    "key": "prop_cafe_espresso_small",
    "file": "prop_cafe_espresso_small.png",
    "w": 49,
    "h": 53,
    "dw": 44
  },
  {
    "key": "prop_cafe_pastry_case",
    "file": "prop_cafe_pastry_case.png",
    "w": 60,
    "h": 49,
    "dw": 60
  },
  {
    "key": "prop_cafe_patio",
    "file": "prop_cafe_patio.png",
    "w": 45,
    "h": 30,
    "dw": 44
  },
  {
    "key": "prop_cafe_menu_a",
    "file": "prop_cafe_menu_a.png",
    "w": 37,
    "h": 46,
    "dw": 28
  },
  {
    "key": "prop_cafe_menu_b",
    "file": "prop_cafe_menu_b.png",
    "w": 38,
    "h": 46,
    "dw": 28
  },
  {
    "key": "prop_cafe_hangplant_a",
    "file": "prop_cafe_hangplant_a.png",
    "w": 55,
    "h": 77,
    "dw": 40
  },
  {
    "key": "prop_cafe_hangplant_b",
    "file": "prop_cafe_hangplant_b.png",
    "w": 34,
    "h": 83,
    "dw": 30
  },
  {
    "key": "prop_cafe_lamp_a",
    "file": "prop_cafe_lamp_a.png",
    "w": 34,
    "h": 54,
    "dw": 30
  },
  {
    "key": "prop_cafe_lamp_b",
    "file": "prop_cafe_lamp_b.png",
    "w": 33,
    "h": 53,
    "dw": 30
  },
  {
    "key": "prop_cafe_counter_dark",
    "file": "prop_cafe_counter_dark.png",
    "w": 72,
    "h": 41,
    "dw": 96
  },
  {
    "key": "prop_cafe_counter_light",
    "file": "prop_cafe_counter_light.png",
    "w": 73,
    "h": 41,
    "dw": 96
  },
  {
    "key": "prop_cafe_counter_pink",
    "file": "prop_cafe_counter_pink.png",
    "w": 73,
    "h": 41,
    "dw": 96
  },
  {
    "key": "prop_cafe_stool_a",
    "file": "prop_cafe_stool_a.png",
    "w": 31,
    "h": 51,
    "dw": 26
  },
  {
    "key": "prop_cafe_stool_b",
    "file": "prop_cafe_stool_b.png",
    "w": 31,
    "h": 52,
    "dw": 26
  },
  {
    "key": "prop_cafe_records",
    "file": "prop_cafe_records.png",
    "w": 89,
    "h": 77,
    "dw": 76
  },
  {
    "key": "prop_cafe_chalkboard",
    "file": "prop_cafe_chalkboard.png",
    "w": 86,
    "h": 121,
    "dw": 64
  }
] as const;
