// Generated by tools/slice_town.py. Do not edit by hand.
export const TOWN_SPRITES = [
  {
    "key": "town_school",
    "file": "town_school.png",
    "w": 124,
    "h": 106,
    "dw": 160
  },
  {
    "key": "town_library",
    "file": "town_library.png",
    "w": 123,
    "h": 107,
    "dw": 130
  },
  {
    "key": "town_station",
    "file": "town_station.png",
    "w": 138,
    "h": 95,
    "dw": 160
  },
  {
    "key": "town_hall",
    "file": "town_hall.png",
    "w": 118,
    "h": 116,
    "dw": 160
  },
  {
    "key": "town_hospital",
    "file": "town_hospital.png",
    "w": 121,
    "h": 110,
    "dw": 130
  },
  {
    "key": "town_fire",
    "file": "town_fire.png",
    "w": 120,
    "h": 110,
    "dw": 130
  },
  {
    "key": "town_bakery",
    "file": "town_bakery.png",
    "w": 117,
    "h": 110,
    "dw": 130
  },
  {
    "key": "town_bank",
    "file": "town_bank.png",
    "w": 119,
    "h": 108,
    "dw": 130
  },
  {
    "key": "town_cinema",
    "file": "town_cinema.png",
    "w": 117,
    "h": 107,
    "dw": 130
  },
  {
    "key": "town_gym",
    "file": "town_gym.png",
    "w": 119,
    "h": 108,
    "dw": 130
  },
  {
    "key": "town_yoga",
    "file": "town_yoga.png",
    "w": 114,
    "h": 108,
    "dw": 130
  },
  {
    "key": "town_petshop",
    "file": "town_petshop.png",
    "w": 114,
    "h": 110,
    "dw": 130
  },
  {
    "key": "town_pavilion",
    "file": "town_pavilion.png",
    "w": 107,
    "h": 95,
    "dw": 128
  },
  {
    "key": "town_arcade",
    "file": "town_arcade.png",
    "w": 104,
    "h": 99,
    "dw": 130
  },
  {
    "key": "town_stage",
    "file": "town_stage.png",
    "w": 94,
    "h": 87,
    "dw": 128
  },
  {
    "key": "town_stalls",
    "file": "town_stalls.png",
    "w": 92,
    "h": 83,
    "dw": 130
  },
  {
    "key": "town_bulletin_1",
    "file": "town_bulletin_1.png",
    "w": 76,
    "h": 88,
    "dw": 50
  },
  {
    "key": "town_bulletin_2",
    "file": "town_bulletin_2.png",
    "w": 77,
    "h": 88,
    "dw": 50
  },
  {
    "key": "town_bulletin_3",
    "file": "town_bulletin_3.png",
    "w": 74,
    "h": 88,
    "dw": 50
  },
  {
    "key": "town_bulletin_4",
    "file": "town_bulletin_4.png",
    "w": 77,
    "h": 88,
    "dw": 50
  },
  {
    "key": "town_well_2",
    "file": "town_well_2.png",
    "w": 75,
    "h": 82,
    "dw": 40
  },
  {
    "key": "town_well_3",
    "file": "town_well_3.png",
    "w": 77,
    "h": 82,
    "dw": 40
  },
  {
    "key": "town_icecream_1",
    "file": "town_icecream_1.png",
    "w": 67,
    "h": 82,
    "dw": 50
  },
  {
    "key": "town_pigeons_idle",
    "file": "town_pigeons_idle.png",
    "w": 28,
    "h": 26,
    "dw": 22
  },
  {
    "key": "town_pigeons_scatter",
    "file": "town_pigeons_scatter.png",
    "w": 25,
    "h": 31,
    "dw": 22
  },
  {
    "key": "town_trash_1",
    "file": "town_trash_1.png",
    "w": 66,
    "h": 81,
    "dw": 40
  },
  {
    "key": "town_trash_2",
    "file": "town_trash_2.png",
    "w": 80,
    "h": 78,
    "dw": 40
  },
  {
    "key": "town_drink_1",
    "file": "town_drink_1.png",
    "w": 66,
    "h": 77,
    "dw": 40
  },
  {
    "key": "town_drink_2",
    "file": "town_drink_2.png",
    "w": 66,
    "h": 76,
    "dw": 40
  },
  {
    "key": "town_news_1",
    "file": "town_news_1.png",
    "w": 71,
    "h": 85,
    "dw": 40
  },
  {
    "key": "town_news_2",
    "file": "town_news_2.png",
    "w": 80,
    "h": 80,
    "dw": 40
  },
  {
    "key": "town_ov_leaves",
    "file": "town_ov_leaves.png",
    "w": 80,
    "h": 34,
    "dw": 40
  },
  {
    "key": "town_fountain_dry",
    "file": "town_fountain_dry.png",
    "w": 80,
    "h": 63,
    "dw": 40
  },
  {
    "key": "town_fountain_flow",
    "file": "town_fountain_flow.png",
    "w": 92,
    "h": 68,
    "dw": 56
  },
  {
    "key": "town_fountain_fest",
    "file": "town_fountain_fest.png",
    "w": 91,
    "h": 71,
    "dw": 56
  },
  {
    "key": "town_bench_straight",
    "file": "town_bench_straight.png",
    "w": 80,
    "h": 52,
    "dw": 40
  },
  {
    "key": "town_bench_curved",
    "file": "town_bench_curved.png",
    "w": 112,
    "h": 61,
    "dw": 56
  },
  {
    "key": "town_flowerbed",
    "file": "town_flowerbed.png",
    "w": 112,
    "h": 71,
    "dw": 56
  },
  {
    "key": "town_planter",
    "file": "town_planter.png",
    "w": 98,
    "h": 79,
    "dw": 56
  },
  {
    "key": "town_clock",
    "file": "town_clock.png",
    "w": 43,
    "h": 90,
    "dw": 26
  },
  {
    "key": "town_stall_fruit",
    "file": "town_stall_fruit.png",
    "w": 74,
    "h": 92,
    "dw": 56
  },
  {
    "key": "town_stall_crafts",
    "file": "town_stall_crafts.png",
    "w": 80,
    "h": 92,
    "dw": 56
  },
  {
    "key": "town_stall_bakery",
    "file": "town_stall_bakery.png",
    "w": 72,
    "h": 90,
    "dw": 56
  }
] as const;
