// Generated by tools/slice_sprites.py. Do not edit by hand.
export const SPRITES = [
  {
    "key": "floor_wood",
    "file": "floor_wood.png",
    "w": 132,
    "h": 86,
    "dw": 66
  },
  {
    "key": "wall_single",
    "file": "wall_single.png",
    "w": 72,
    "h": 124,
    "dw": 36
  },
  {
    "key": "wall_corner",
    "file": "wall_corner.png",
    "w": 120,
    "h": 128,
    "dw": 60
  },
  {
    "key": "wall_window",
    "file": "wall_window.png",
    "w": 86,
    "h": 129,
    "dw": 43
  },
  {
    "key": "wall_door",
    "file": "wall_door.png",
    "w": 76,
    "h": 133,
    "dw": 38
  },
  {
    "key": "bed_gingham",
    "file": "bed_gingham.png",
    "w": 200,
    "h": 176,
    "dw": 100
  },
  {
    "key": "nightstand",
    "file": "nightstand.png",
    "w": 88,
    "h": 116,
    "dw": 44
  },
  {
    "key": "chair_sage",
    "file": "chair_sage.png",
    "w": 80,
    "h": 112,
    "dw": 40
  },
  {
    "key": "mug",
    "file": "mug.png",
    "w": 44,
    "h": 42,
    "dw": 22
  },
  {
    "key": "xmas_tree",
    "file": "xmas_tree.png",
    "w": 88,
    "h": 161,
    "dw": 44
  },
  {
    "key": "blanket_red",
    "file": "blanket_red.png",
    "w": 112,
    "h": 109,
    "dw": 56
  },
  {
    "key": "tree_spring",
    "file": "tree_spring.png",
    "w": 71,
    "h": 97,
    "dw": 38
  },
  {
    "key": "tree_summer",
    "file": "tree_summer.png",
    "w": 72,
    "h": 97,
    "dw": 38
  },
  {
    "key": "tree_autumn",
    "file": "tree_autumn.png",
    "w": 76,
    "h": 93,
    "dw": 38
  },
  {
    "key": "tree_winter",
    "file": "tree_winter.png",
    "w": 72,
    "h": 97,
    "dw": 40
  },
  {
    "key": "blanket_spring",
    "file": "blanket_spring.png",
    "w": 100,
    "h": 80,
    "dw": 50
  },
  {
    "key": "blanket_summer",
    "file": "blanket_summer.png",
    "w": 100,
    "h": 82,
    "dw": 50
  },
  {
    "key": "blanket_autumn",
    "file": "blanket_autumn.png",
    "w": 100,
    "h": 80,
    "dw": 50
  },
  {
    "key": "blanket_winter",
    "file": "blanket_winter.png",
    "w": 97,
    "h": 81,
    "dw": 50
  },
  {
    "key": "cafe_exterior",
    "file": "cafe_exterior.png",
    "w": 240,
    "h": 200,
    "dw": 120
  },
  {
    "key": "wooden_chair_a",
    "file": "wooden_chair_a.png",
    "w": 67,
    "h": 102,
    "dw": 34
  },
  {
    "key": "wooden_chair_b",
    "file": "wooden_chair_b.png",
    "w": 65,
    "h": 102,
    "dw": 34
  },
  {
    "key": "cushion_set",
    "file": "cushion_set.png",
    "w": 175,
    "h": 95,
    "dw": 100
  },
  {
    "key": "round_table_set",
    "file": "round_table_set.png",
    "w": 154,
    "h": 114,
    "dw": 90
  },
  {
    "key": "square_table_set",
    "file": "square_table_set.png",
    "w": 173,
    "h": 109,
    "dw": 100
  },
  {
    "key": "bookshelf_cafe",
    "file": "bookshelf_cafe.png",
    "w": 82,
    "h": 88,
    "dw": 44
  },
  {
    "key": "counter_pastry",
    "file": "counter_pastry.png",
    "w": 215,
    "h": 146,
    "dw": 150
  },
  {
    "key": "food_matcha",
    "file": "food_matcha.png",
    "w": 56,
    "h": 42,
    "dw": 28
  },
  {
    "key": "food_tray",
    "file": "food_tray.png",
    "w": 64,
    "h": 41,
    "dw": 32
  },
  {
    "key": "food_cake_a",
    "file": "food_cake_a.png",
    "w": 56,
    "h": 44,
    "dw": 28
  },
  {
    "key": "food_cake_b",
    "file": "food_cake_b.png",
    "w": 56,
    "h": 40,
    "dw": 28
  },
  {
    "key": "food_slice",
    "file": "food_slice.png",
    "w": 56,
    "h": 44,
    "dw": 28
  },
  {
    "key": "food_croissant",
    "file": "food_croissant.png",
    "w": 60,
    "h": 49,
    "dw": 30
  },
  {
    "key": "food_display",
    "file": "food_display.png",
    "w": 64,
    "h": 48,
    "dw": 32
  },
  {
    "key": "food_macarons",
    "file": "food_macarons.png",
    "w": 60,
    "h": 41,
    "dw": 30
  },
  {
    "key": "food_loaf",
    "file": "food_loaf.png",
    "w": 60,
    "h": 42,
    "dw": 30
  },
  {
    "key": "food_bread",
    "file": "food_bread.png",
    "w": 56,
    "h": 48,
    "dw": 28
  },
  {
    "key": "plant_a",
    "file": "plant_a.png",
    "w": 55,
    "h": 70,
    "dw": 30
  },
  {
    "key": "plant_b",
    "file": "plant_b.png",
    "w": 46,
    "h": 60,
    "dw": 28
  },
  {
    "key": "plant_snake",
    "file": "plant_snake.png",
    "w": 46,
    "h": 77,
    "dw": 26
  },
  {
    "key": "lamp",
    "file": "lamp.png",
    "w": 39,
    "h": 62,
    "dw": 22
  },
  {
    "key": "menu_sign",
    "file": "menu_sign.png",
    "w": 48,
    "h": 67,
    "dw": 24
  },
  {
    "key": "suitcase",
    "file": "suitcase.png",
    "w": 56,
    "h": 52,
    "dw": 28
  },
  {
    "key": "couch_sectional",
    "file": "couch_sectional.png",
    "w": 236,
    "h": 152,
    "dw": 150
  },
  {
    "key": "pastry_case",
    "file": "pastry_case.png",
    "w": 200,
    "h": 187,
    "dw": 100
  },
  {
    "key": "bread_shelf",
    "file": "bread_shelf.png",
    "w": 168,
    "h": 180,
    "dw": 84
  },
  {
    "key": "menu_stand_a",
    "file": "menu_stand_a.png",
    "w": 52,
    "h": 75,
    "dw": 26
  },
  {
    "key": "menu_stand_b",
    "file": "menu_stand_b.png",
    "w": 56,
    "h": 81,
    "dw": 28
  },
  {
    "key": "plush_kitty",
    "file": "plush_kitty.png",
    "w": 68,
    "h": 87,
    "dw": 34
  },
  {
    "key": "plush_miffy",
    "file": "plush_miffy.png",
    "w": 64,
    "h": 105,
    "dw": 32
  },
  {
    "key": "palm_grove",
    "file": "palm_grove.png",
    "w": 191,
    "h": 210,
    "dw": 100
  },
  {
    "key": "lifeguard_stand",
    "file": "lifeguard_stand.png",
    "w": 108,
    "h": 128,
    "dw": 76
  },
  {
    "key": "surfboards",
    "file": "surfboards.png",
    "w": 44,
    "h": 75,
    "dw": 28
  },
  {
    "key": "lighthouse",
    "file": "lighthouse.png",
    "w": 215,
    "h": 257,
    "dw": 130
  },
  {
    "key": "miniso",
    "file": "miniso.png",
    "w": 203,
    "h": 146,
    "dw": 130
  },
  {
    "key": "home_house",
    "file": "home_house.png",
    "w": 198,
    "h": 148,
    "dw": 130
  },
  {
    "key": "cottage",
    "file": "cottage.png",
    "w": 117,
    "h": 131,
    "dw": 80
  },
  {
    "key": "pet_golden",
    "file": "pet_golden.png",
    "w": 92,
    "h": 71,
    "dw": 46
  },
  {
    "key": "pet_corgi",
    "file": "pet_corgi.png",
    "w": 67,
    "h": 83,
    "dw": 34
  },
  {
    "key": "pet_bunny",
    "file": "pet_bunny.png",
    "w": 44,
    "h": 65,
    "dw": 22
  },
  {
    "key": "lamp_floor",
    "file": "lamp_floor.png",
    "w": 68,
    "h": 100,
    "dw": 34
  },
  {
    "key": "bed_wood",
    "file": "bed_wood.png",
    "w": 200,
    "h": 145,
    "dw": 100
  },
  {
    "key": "bookshelf_small",
    "file": "bookshelf_small.png",
    "w": 100,
    "h": 113,
    "dw": 50
  },
  {
    "key": "plant_floor",
    "file": "plant_floor.png",
    "w": 80,
    "h": 140,
    "dw": 40
  },
  {
    "key": "wreath_holiday",
    "file": "wreath_holiday.png",
    "w": 68,
    "h": 75,
    "dw": 34
  },
  {
    "key": "string_lights",
    "file": "string_lights.png",
    "w": 112,
    "h": 98,
    "dw": 56
  },
  {
    "key": "print_palm",
    "file": "print_palm.png",
    "w": 44,
    "h": 81,
    "dw": 22
  },
  {
    "key": "print_coffee",
    "file": "print_coffee.png",
    "w": 44,
    "h": 79,
    "dw": 22
  },
  {
    "key": "print_sunset",
    "file": "print_sunset.png",
    "w": 48,
    "h": 86,
    "dw": 24
  },
  {
    "key": "shelf_plant",
    "file": "shelf_plant.png",
    "w": 68,
    "h": 63,
    "dw": 34
  },
  {
    "key": "shelf_books",
    "file": "shelf_books.png",
    "w": 68,
    "h": 45,
    "dw": 34
  },
  {
    "key": "latte_gold",
    "file": "latte_gold.png",
    "w": 56,
    "h": 53,
    "dw": 28
  },
  {
    "key": "pastry_trio",
    "file": "pastry_trio.png",
    "w": 68,
    "h": 49,
    "dw": 34
  },
  {
    "key": "wreath_xmas",
    "file": "wreath_xmas.png",
    "w": 72,
    "h": 73,
    "dw": 36
  },
  {
    "key": "garland_stars",
    "file": "garland_stars.png",
    "w": 112,
    "h": 52,
    "dw": 56
  },
  {
    "key": "wreath_spring",
    "file": "wreath_spring.png",
    "w": 68,
    "h": 62,
    "dw": 34
  },
  {
    "key": "garland_spring",
    "file": "garland_spring.png",
    "w": 112,
    "h": 39,
    "dw": 56
  },
  {
    "key": "wreath_summer",
    "file": "wreath_summer.png",
    "w": 68,
    "h": 64,
    "dw": 34
  },
  {
    "key": "garland_summer",
    "file": "garland_summer.png",
    "w": 104,
    "h": 42,
    "dw": 56
  },
  {
    "key": "wreath_autumn",
    "file": "wreath_autumn.png",
    "w": 68,
    "h": 64,
    "dw": 34
  },
  {
    "key": "garland_autumn",
    "file": "garland_autumn.png",
    "w": 112,
    "h": 41,
    "dw": 56
  },
  {
    "key": "wreath_winter",
    "file": "wreath_winter.png",
    "w": 68,
    "h": 65,
    "dw": 34
  },
  {
    "key": "garland_winter",
    "file": "garland_winter.png",
    "w": 112,
    "h": 40,
    "dw": 56
  },
  {
    "key": "kitty_o1",
    "file": "kitty_o1.png",
    "w": 64,
    "h": 73,
    "dw": 32
  },
  {
    "key": "kitty_o2",
    "file": "kitty_o2.png",
    "w": 64,
    "h": 71,
    "dw": 32
  },
  {
    "key": "kitty_o4",
    "file": "kitty_o4.png",
    "w": 64,
    "h": 76,
    "dw": 32
  },
  {
    "key": "kitty_picnic",
    "file": "kitty_picnic.png",
    "w": 138,
    "h": 100,
    "dw": 76
  },
  {
    "key": "miffy_sweater",
    "file": "miffy_sweater.png",
    "w": 60,
    "h": 91,
    "dw": 30
  },
  {
    "key": "miffy_raincoat",
    "file": "miffy_raincoat.png",
    "w": 60,
    "h": 103,
    "dw": 30
  },
  {
    "key": "miffy_boots",
    "file": "miffy_boots.png",
    "w": 60,
    "h": 124,
    "dw": 30
  },
  {
    "key": "camp_site",
    "file": "camp_site.png",
    "w": 280,
    "h": 277,
    "dw": 140
  },
  {
    "key": "snoopy_o1",
    "file": "snoopy_o1.png",
    "w": 68,
    "h": 99,
    "dw": 34
  },
  {
    "key": "snoopy_o2",
    "file": "snoopy_o2.png",
    "w": 67,
    "h": 137,
    "dw": 34
  },
  {
    "key": "snoopy_o3",
    "file": "snoopy_o3.png",
    "w": 68,
    "h": 113,
    "dw": 34
  },
  {
    "key": "snoopy_o4",
    "file": "snoopy_o4.png",
    "w": 64,
    "h": 119,
    "dw": 32
  },
  {
    "key": "rv_a",
    "file": "rv_a.png",
    "w": 163,
    "h": 141,
    "dw": 120
  },
  {
    "key": "rv_b",
    "file": "rv_b.png",
    "w": 164,
    "h": 136,
    "dw": 120
  },
  {
    "key": "lantern_camp",
    "file": "lantern_camp.png",
    "w": 40,
    "h": 70,
    "dw": 20
  },
  {
    "key": "lantern_soft",
    "file": "lantern_soft.png",
    "w": 40,
    "h": 70,
    "dw": 20
  },
  {
    "key": "lantern_oil",
    "file": "lantern_oil.png",
    "w": 40,
    "h": 60,
    "dw": 20
  },
  {
    "key": "sleeping_bag_a",
    "file": "sleeping_bag_a.png",
    "w": 68,
    "h": 52,
    "dw": 34
  },
  {
    "key": "sleeping_bag_b",
    "file": "sleeping_bag_b.png",
    "w": 68,
    "h": 53,
    "dw": 34
  },
  {
    "key": "sleeping_bag_pink",
    "file": "sleeping_bag_pink.png",
    "w": 68,
    "h": 53,
    "dw": 34
  },
  {
    "key": "mugs_enamel",
    "file": "mugs_enamel.png",
    "w": 52,
    "h": 42,
    "dw": 26
  },
  {
    "key": "coffee_pot",
    "file": "coffee_pot.png",
    "w": 40,
    "h": 58,
    "dw": 20
  },
  {
    "key": "camp_percolator",
    "file": "camp_percolator.png",
    "w": 44,
    "h": 52,
    "dw": 22
  },
  {
    "key": "firewood",
    "file": "firewood.png",
    "w": 56,
    "h": 45,
    "dw": 28
  },
  {
    "key": "cooler",
    "file": "cooler.png",
    "w": 68,
    "h": 69,
    "dw": 34
  },
  {
    "key": "radio",
    "file": "radio.png",
    "w": 56,
    "h": 59,
    "dw": 28
  },
  {
    "key": "camp_stove",
    "file": "camp_stove.png",
    "w": 55,
    "h": 63,
    "dw": 28
  },
  {
    "key": "camp_pan",
    "file": "camp_pan.png",
    "w": 64,
    "h": 44,
    "dw": 32
  },
  {
    "key": "camp_chair_pink",
    "file": "camp_chair_pink.png",
    "w": 72,
    "h": 75,
    "dw": 36
  },
  {
    "key": "camp_chair_blue",
    "file": "camp_chair_blue.png",
    "w": 72,
    "h": 95,
    "dw": 36
  },
  {
    "key": "bedding_cozy",
    "file": "bedding_cozy.png",
    "w": 140,
    "h": 103,
    "dw": 70
  },
  {
    "key": "plant_rack",
    "file": "plant_rack.png",
    "w": 68,
    "h": 106,
    "dw": 34
  },
  {
    "key": "books_blanket",
    "file": "books_blanket.png",
    "w": 56,
    "h": 46,
    "dw": 28
  },
  {
    "key": "pet_bed",
    "file": "pet_bed.png",
    "w": 68,
    "h": 50,
    "dw": 34
  },
  {
    "key": "laundry_basket",
    "file": "laundry_basket.png",
    "w": 58,
    "h": 53,
    "dw": 30
  },
  {
    "key": "kitchenette",
    "file": "kitchenette.png",
    "w": 140,
    "h": 113,
    "dw": 70
  },
  {
    "key": "dinette_seating",
    "file": "dinette_seating.png",
    "w": 160,
    "h": 112,
    "dw": 80
  },
  {
    "key": "cabinet_shelving",
    "file": "cabinet_shelving.png",
    "w": 102,
    "h": 149,
    "dw": 56
  },
  {
    "key": "bathroom_module",
    "file": "bathroom_module.png",
    "w": 112,
    "h": 142,
    "dw": 56
  },
  {
    "key": "shop_bookstore",
    "file": "shop_bookstore.png",
    "w": 181,
    "h": 197,
    "dw": 110
  },
  {
    "key": "shop_bistro",
    "file": "shop_bistro.png",
    "w": 208,
    "h": 198,
    "dw": 110
  },
  {
    "key": "shop_florist",
    "file": "shop_florist.png",
    "w": 178,
    "h": 182,
    "dw": 100
  },
  {
    "key": "shop_toy",
    "file": "shop_toy.png",
    "w": 191,
    "h": 202,
    "dw": 110
  },
  {
    "key": "stand_news",
    "file": "stand_news.png",
    "w": 96,
    "h": 134,
    "dw": 56
  },
  {
    "key": "stand_hotdog",
    "file": "stand_hotdog.png",
    "w": 125,
    "h": 141,
    "dw": 64
  },
  {
    "key": "stand_art",
    "file": "stand_art.png",
    "w": 134,
    "h": 137,
    "dw": 70
  },
  {
    "key": "board_message",
    "file": "board_message.png",
    "w": 107,
    "h": 146,
    "dw": 64
  },
  {
    "key": "street_lamp_a",
    "file": "street_lamp_a.png",
    "w": 40,
    "h": 147,
    "dw": 20
  },
  {
    "key": "street_lamp_b",
    "file": "street_lamp_b.png",
    "w": 48,
    "h": 134,
    "dw": 24
  },
  {
    "key": "street_lamp_c",
    "file": "street_lamp_c.png",
    "w": 40,
    "h": 155,
    "dw": 20
  },
  {
    "key": "street_lamp_d",
    "file": "street_lamp_d.png",
    "w": 48,
    "h": 146,
    "dw": 24
  },
  {
    "key": "bench_a",
    "file": "bench_a.png",
    "w": 92,
    "h": 88,
    "dw": 46
  },
  {
    "key": "bench_b",
    "file": "bench_b.png",
    "w": 92,
    "h": 92,
    "dw": 46
  },
  {
    "key": "bench_c",
    "file": "bench_c.png",
    "w": 92,
    "h": 90,
    "dw": 46
  },
  {
    "key": "bench_d",
    "file": "bench_d.png",
    "w": 92,
    "h": 96,
    "dw": 46
  },
  {
    "key": "planter_pot",
    "file": "planter_pot.png",
    "w": 56,
    "h": 67,
    "dw": 28
  },
  {
    "key": "planter_box_a",
    "file": "planter_box_a.png",
    "w": 88,
    "h": 99,
    "dw": 44
  },
  {
    "key": "plant_tall",
    "file": "plant_tall.png",
    "w": 68,
    "h": 117,
    "dw": 34
  },
  {
    "key": "planter_box_b",
    "file": "planter_box_b.png",
    "w": 88,
    "h": 100,
    "dw": 44
  },
  {
    "key": "phone_booth",
    "file": "phone_booth.png",
    "w": 80,
    "h": 172,
    "dw": 40
  },
  {
    "key": "bus_sign",
    "file": "bus_sign.png",
    "w": 40,
    "h": 145,
    "dw": 20
  },
  {
    "key": "clock_post",
    "file": "clock_post.png",
    "w": 56,
    "h": 162,
    "dw": 28
  },
  {
    "key": "wall_clock",
    "file": "wall_clock.png",
    "w": 72,
    "h": 81,
    "dw": 36
  },
  {
    "key": "bin_a",
    "file": "bin_a.png",
    "w": 44,
    "h": 61,
    "dw": 22
  },
  {
    "key": "bin_b",
    "file": "bin_b.png",
    "w": 44,
    "h": 58,
    "dw": 22
  },
  {
    "key": "npc_grandma",
    "file": "npc_grandma.png",
    "w": 60,
    "h": 116,
    "dw": 30
  },
  {
    "key": "npc_photographer",
    "file": "npc_photographer.png",
    "w": 60,
    "h": 142,
    "dw": 30
  },
  {
    "key": "npc_woman",
    "file": "npc_woman.png",
    "w": 56,
    "h": 153,
    "dw": 28
  },
  {
    "key": "npc_hat",
    "file": "npc_hat.png",
    "w": 56,
    "h": 147,
    "dw": 28
  },
  {
    "key": "bw_light",
    "file": "bw_light.png",
    "w": 132,
    "h": 64,
    "dw": 66
  },
  {
    "key": "bw_light2",
    "file": "bw_light2.png",
    "w": 132,
    "h": 63,
    "dw": 66
  },
  {
    "key": "bw_coral",
    "file": "bw_coral.png",
    "w": 132,
    "h": 63,
    "dw": 66
  },
  {
    "key": "bw_dark",
    "file": "bw_dark.png",
    "w": 132,
    "h": 74,
    "dw": 66
  },
  {
    "key": "bw_brown",
    "file": "bw_brown.png",
    "w": 132,
    "h": 72,
    "dw": 66
  },
  {
    "key": "bw_green",
    "file": "bw_green.png",
    "w": 132,
    "h": 78,
    "dw": 66
  },
  {
    "key": "bw_coral2",
    "file": "bw_coral2.png",
    "w": 132,
    "h": 76,
    "dw": 66
  },
  {
    "key": "bw_sand",
    "file": "bw_sand.png",
    "w": 132,
    "h": 79,
    "dw": 66
  },
  {
    "key": "shop_surf",
    "file": "shop_surf.png",
    "w": 170,
    "h": 157,
    "dw": 90
  },
  {
    "key": "shop_icecream",
    "file": "shop_icecream.png",
    "w": 148,
    "h": 143,
    "dw": 74
  },
  {
    "key": "stand_coffee",
    "file": "stand_coffee.png",
    "w": 123,
    "h": 152,
    "dw": 64
  },
  {
    "key": "shop_souvenir",
    "file": "shop_souvenir.png",
    "w": 185,
    "h": 156,
    "dw": 100
  },
  {
    "key": "lifeguard_red",
    "file": "lifeguard_red.png",
    "w": 115,
    "h": 192,
    "dw": 60
  },
  {
    "key": "surfboard_rack",
    "file": "surfboard_rack.png",
    "w": 88,
    "h": 106,
    "dw": 44
  },
  {
    "key": "surfboard_stack",
    "file": "surfboard_stack.png",
    "w": 100,
    "h": 168,
    "dw": 50
  },
  {
    "key": "volleyball_net",
    "file": "volleyball_net.png",
    "w": 220,
    "h": 190,
    "dw": 110
  },
  {
    "key": "beach_set",
    "file": "beach_set.png",
    "w": 152,
    "h": 138,
    "dw": 76
  },
  {
    "key": "souvenir_display",
    "file": "souvenir_display.png",
    "w": 80,
    "h": 105,
    "dw": 40
  },
  {
    "key": "seating_cluster",
    "file": "seating_cluster.png",
    "w": 180,
    "h": 125,
    "dw": 90
  },
  {
    "key": "region_farm",
    "file": "region_farm.png",
    "w": 492,
    "h": 326,
    "dw": 300
  },
  {
    "key": "region_mountain",
    "file": "region_mountain.png",
    "w": 382,
    "h": 362,
    "dw": 260
  },
  {
    "key": "campus_buildings",
    "file": "campus_buildings.png",
    "w": 406,
    "h": 216,
    "dw": 220
  },
  {
    "key": "greenhouse_domes",
    "file": "greenhouse_domes.png",
    "w": 274,
    "h": 204,
    "dw": 170
  },
  {
    "key": "farm_tools",
    "file": "farm_tools.png",
    "w": 80,
    "h": 45,
    "dw": 40
  },
  {
    "key": "crate_veg",
    "file": "crate_veg.png",
    "w": 60,
    "h": 28,
    "dw": 30
  },
  {
    "key": "orange_tree",
    "file": "orange_tree.png",
    "w": 49,
    "h": 80,
    "dw": 28
  },
  {
    "key": "telescope",
    "file": "telescope.png",
    "w": 52,
    "h": 78,
    "dw": 26
  },
  {
    "key": "hiking_poles",
    "file": "hiking_poles.png",
    "w": 28,
    "h": 67,
    "dw": 14
  },
  {
    "key": "golf_cart",
    "file": "golf_cart.png",
    "w": 80,
    "h": 74,
    "dw": 40
  },
  {
    "key": "vertical_farm",
    "file": "vertical_farm.png",
    "w": 72,
    "h": 98,
    "dw": 36
  },
  {
    "key": "rachel_front",
    "file": "rachel_front.png",
    "w": 62,
    "h": 114,
    "dw": 31
  },
  {
    "key": "rachel_side",
    "file": "rachel_side.png",
    "w": 58,
    "h": 110,
    "dw": 29
  },
  {
    "key": "rachel_back",
    "file": "rachel_back.png",
    "w": 54,
    "h": 106,
    "dw": 27
  }
] as const;

export const WALK_SHEET = { key: "james_walk", file: "james_walk.png", frameWidth: 68, frameHeight: 114, rows: ["front", "back", "left", "right"] } as const;
