// Generated by tools/slice_paths.py. Do not edit by hand.
export const PATH_SPRITES = [
  {
    "key": "path_card_rv",
    "file": "path_card_rv.png",
    "w": 131,
    "h": 88,
    "dw": 70
  },
  {
    "key": "path_card_shop",
    "file": "path_card_shop.png",
    "w": 140,
    "h": 118,
    "dw": 70
  },
  {
    "key": "path_card_home",
    "file": "path_card_home.png",
    "w": 116,
    "h": 72,
    "dw": 70
  },
  {
    "key": "path_rv_1",
    "file": "path_rv_1.png",
    "w": 144,
    "h": 117,
    "dw": 62
  },
  {
    "key": "path_rv_2",
    "file": "path_rv_2.png",
    "w": 180,
    "h": 111,
    "dw": 62
  },
  {
    "key": "path_rv_3",
    "file": "path_rv_3.png",
    "w": 183,
    "h": 132,
    "dw": 62
  },
  {
    "key": "path_rv_4",
    "file": "path_rv_4.png",
    "w": 225,
    "h": 135,
    "dw": 62
  },
  {
    "key": "path_shop_1",
    "file": "path_shop_1.png",
    "w": 171,
    "h": 135,
    "dw": 62
  },
  {
    "key": "path_shop_2",
    "file": "path_shop_2.png",
    "w": 171,
    "h": 123,
    "dw": 62
  },
  {
    "key": "path_shop_3",
    "file": "path_shop_3.png",
    "w": 153,
    "h": 132,
    "dw": 62
  },
  {
    "key": "path_shop_4",
    "file": "path_shop_4.png",
    "w": 189,
    "h": 135,
    "dw": 62
  },
  {
    "key": "path_home_1",
    "file": "path_home_1.png",
    "w": 174,
    "h": 135,
    "dw": 62
  },
  {
    "key": "path_home_2",
    "file": "path_home_2.png",
    "w": 174,
    "h": 135,
    "dw": 62
  },
  {
    "key": "path_home_3",
    "file": "path_home_3.png",
    "w": 159,
    "h": 135,
    "dw": 62
  },
  {
    "key": "path_home_4",
    "file": "path_home_4.png",
    "w": 210,
    "h": 153,
    "dw": 62
  }
] as const;
