// Generated by tools/slice_starters.py. Do not edit by hand.
export const STARTER_SPRITES = [
  {
    "key": "starter_rv_1",
    "file": "starter_rv_1.png",
    "w": 230,
    "h": 147,
    "dw": 115
  },
  {
    "key": "starter_rv_2",
    "file": "starter_rv_2.png",
    "w": 230,
    "h": 149,
    "dw": 115
  },
  {
    "key": "starter_rv_3",
    "file": "starter_rv_3.png",
    "w": 230,
    "h": 141,
    "dw": 115
  },
  {
    "key": "starter_shop_1",
    "file": "starter_shop_1.png",
    "w": 230,
    "h": 224,
    "dw": 115
  },
  {
    "key": "starter_shop_2",
    "file": "starter_shop_2.png",
    "w": 230,
    "h": 194,
    "dw": 115
  },
  {
    "key": "starter_shop_3",
    "file": "starter_shop_3.png",
    "w": 230,
    "h": 203,
    "dw": 115
  },
  {
    "key": "starter_home_1",
    "file": "starter_home_1.png",
    "w": 230,
    "h": 225,
    "dw": 115
  },
  {
    "key": "starter_home_2",
    "file": "starter_home_2.png",
    "w": 230,
    "h": 221,
    "dw": 115
  },
  {
    "key": "starter_home_3",
    "file": "starter_home_3.png",
    "w": 230,
    "h": 201,
    "dw": 115
  }
] as const;
