// Generated by tools/slice_starters2.py. Do not edit by hand.
export const START_SPRITES = [
  {
    "key": "start_rv",
    "file": "start_rv.png",
    "w": 280,
    "h": 193,
    "dw": 140
  },
  {
    "key": "start_shop",
    "file": "start_shop.png",
    "w": 260,
    "h": 211,
    "dw": 130
  },
  {
    "key": "start_home",
    "file": "start_home.png",
    "w": 280,
    "h": 197,
    "dw": 140
  },
  {
    "key": "start_packs",
    "file": "start_packs.png",
    "w": 88,
    "h": 87,
    "dw": 44
  },
  {
    "key": "start_duffel",
    "file": "start_duffel.png",
    "w": 88,
    "h": 81,
    "dw": 44
  },
  {
    "key": "start_toolbox_rv",
    "file": "start_toolbox_rv.png",
    "w": 68,
    "h": 72,
    "dw": 34
  },
  {
    "key": "start_campfire",
    "file": "start_campfire.png",
    "w": 80,
    "h": 76,
    "dw": 40
  },
  {
    "key": "start_stool_a",
    "file": "start_stool_a.png",
    "w": 60,
    "h": 68,
    "dw": 16
  },
  {
    "key": "start_stool_b",
    "file": "start_stool_b.png",
    "w": 60,
    "h": 67,
    "dw": 16
  },
  {
    "key": "start_stool_c",
    "file": "start_stool_c.png",
    "w": 60,
    "h": 70,
    "dw": 16
  },
  {
    "key": "start_cafe_table",
    "file": "start_cafe_table.png",
    "w": 92,
    "h": 53,
    "dw": 46
  },
  {
    "key": "start_cafe_umbrella",
    "file": "start_cafe_umbrella.png",
    "w": 92,
    "h": 104,
    "dw": 46
  },
  {
    "key": "start_cafe_shelf",
    "file": "start_cafe_shelf.png",
    "w": 72,
    "h": 78,
    "dw": 36
  },
  {
    "key": "start_menu_board",
    "file": "start_menu_board.png",
    "w": 60,
    "h": 82,
    "dw": 30
  },
  {
    "key": "start_lumber",
    "file": "start_lumber.png",
    "w": 108,
    "h": 86,
    "dw": 54
  },
  {
    "key": "start_frames",
    "file": "start_frames.png",
    "w": 80,
    "h": 100,
    "dw": 40
  },
  {
    "key": "start_wall_unit",
    "file": "start_wall_unit.png",
    "w": 108,
    "h": 74,
    "dw": 54
  },
  {
    "key": "start_toolbox_home",
    "file": "start_toolbox_home.png",
    "w": 64,
    "h": 66,
    "dw": 32
  }
] as const;
