// Generated by tools/slice_walks.py. Do not edit by hand.
export const WALK_STRIPS = {
  "james_walk_side": {
    "frames": 7,
    "fw": 61,
    "fh": 116
  },
  "rachel_walk_side": {
    "frames": 7,
    "fw": 55,
    "fh": 104
  },
  "dog_walk_side": {
    "frames": 7,
    "fw": 71,
    "fh": 54
  }
} as const;
