// Generated by tools/slice_walks.py. Do not edit by hand.
export const WALK_STRIPS = {
  "james_new": {
    "frames": 8,
    "fw": 52,
    "fh": 106
  },
  "rachel_new": {
    "frames": 7,
    "fw": 56,
    "fh": 102
  },
  "james_dark": {
    "frames": 9,
    "fw": 59,
    "fh": 106
  },
  "rachel_dark": {
    "frames": 9,
    "fw": 56,
    "fh": 102
  },
  "dog_walk_side": {
    "frames": 7,
    "fw": 71,
    "fh": 54
  }
} as const;
