"""Cuts the NPC walk cycles out of art/source/sheet40_npc_walks.jpg.

The sheet is a grid on a cream background. Each figure is isolated by flood filling the background (and the soft
baked shadow) from outside, then bottom aligned into equal frames and saved as one horizontal strip per direction.
Run:  python3 tools/slice_npcs.py
Writes public/assets/sprites/npc_<name>_<dir>.png and src/game/npcSheets.ts.
"""
import json, os
import numpy as np
from PIL import Image
from scipy import ndimage

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, 'art', 'source', 'sheet40_npc_walks.jpg')
OUT = os.path.join(ROOT, 'public', 'assets', 'sprites')

# name -> list of (direction, (x0, y0, x1, y1) of one row of frames, expected frame count)
# Directions describe how the figure is drawn: 'e' faces screen right, 'w' faces screen left, 's' faces the camera.
# The sheet's own N S E W labels are unreliable, so these were set by looking at every row. Rows that repeat another
# facing or change costume were left out. The sheet has no back views, and the student row mixes six different people.
ROWS = {
    'elder':    [('w', (10, 160, 272, 275), 4), ('s', (10, 325, 272, 440), 4)],
    'photo':    [('s', (275, 160, 545, 275), 4), ('s2', (275, 325, 545, 440), 4), ('e', (275, 470, 545, 590), 4)],
    'hiker':    [('e', (548, 160, 810, 275), 4), ('s', (548, 325, 810, 440), 4), ('w', (548, 470, 810, 590), 4)],
    'sunhat':   [('e', (815, 160, 1080, 275), 4), ('s', (815, 325, 1080, 440), 4)],
    'courier':  [('e', (30, 655, 545, 790), 6)],
}


def background_mask(rgb):
    r, g, b = rgb[..., 0], rgb[..., 1], rgb[..., 2]
    lum = (r + g + b) / 3
    spread = rgb.max(-1) - rgb.min(-1)
    cream = (lum > 200) & (spread < 32)
    shadow = (lum > 165) & (lum < 225) & (r - g > 6) & (r - g < 38) & (g - b > -8) & (g - b < 14) & (spread < 45)
    return cream | shadow


def cut(img, box):
    x0, y0, x1, y1 = box
    crop = img[y0:y1, x0:x1]
    bg = background_mask(crop)
    # flood from the crop edges through background-like pixels
    lab, _ = ndimage.label(bg)
    edge_labels = set(np.unique(np.concatenate([lab[0], lab[-1], lab[:, 0], lab[:, -1]]))) - {0}
    outside = np.isin(lab, list(edge_labels))
    fg = ~outside
    fg = ndimage.binary_opening(fg, iterations=1)
    return crop, fg


def figures(crop, fg, n):
    lab, k = ndimage.label(ndimage.binary_dilation(fg, iterations=2))
    objs = ndimage.find_objects(lab)
    items = []
    for i, sl in enumerate(objs):
        area = (lab[sl] == i + 1).sum()
        if area < 500:
            continue
        items.append((sl[1].start, sl))
    items.sort(key=lambda t: t[0])
    return [sl for _, sl in items]


def main():
    img = np.array(Image.open(SRC).convert('RGB')).astype(int)
    os.makedirs(OUT, exist_ok=True)
    meta = {}
    for name, rows in ROWS.items():
        for d, box, n in rows:
            crop, fg = cut(img, box)
            figs = figures(crop, fg, n)
            if len(figs) != n:
                print('WARN', name, d, 'found', len(figs), 'expected', n)
            cells = []
            for sl in figs:
                sub = crop[sl]
                m = ndimage.binary_dilation(fg[sl], iterations=0) & fg[sl]
                a = (m * 255).astype(np.uint8)
                a = np.array(Image.fromarray(a).filter(__import__('PIL.ImageFilter', fromlist=['x']).GaussianBlur(0.6)))
                rgba = np.dstack([sub.astype(np.uint8), a])
                cells.append(Image.fromarray(rgba, 'RGBA'))
            meta[(name, d)] = cells
    # one frame size per character so every direction lines up
    out = {}
    for name, rows in ROWS.items():
        cs = [c for d, _, _ in rows for c in meta[(name, d)]]
        if not cs:
            continue
        fw = max(c.width for c in cs) + 2
        fh = max(c.height for c in cs) + 2
        for d, _, _ in rows:
            cells = meta[(name, d)]
            strip = Image.new('RGBA', (fw * len(cells), fh), (0, 0, 0, 0))
            for i, c in enumerate(cells):
                strip.paste(c, (i * fw + (fw - c.width) // 2, fh - c.height - 1))  # bottom aligned, centred
            key = f'npc_{name}_{d}'
            strip.save(os.path.join(OUT, key + '.png'))
            out[key] = {'frames': len(cells), 'fw': fw, 'fh': fh}
    with open(os.path.join(ROOT, 'src', 'game', 'npcSheets.ts'), 'w') as f:
        f.write('// Generated by tools/slice_npcs.py. Do not edit by hand.\n')
        f.write('export const NPC_STRIPS = ' + json.dumps(out, indent=2) + ' as const;\n')
    print(json.dumps(out))


if __name__ == '__main__':
    main()
