"""Cuts the starter structure growth stages (RV, Shop and Café, Home Foundation) from sheet 36.
Run:  python3 tools/slice_starters.py   Writes public/assets/sprites/starter_*.png and src/game/spriteListStarters.ts
"""
import importlib.util, json, os
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
spec = importlib.util.spec_from_file_location('s41', os.path.join(HERE, 'slice_sheets41_45.py'))
s41 = importlib.util.module_from_spec(spec)
spec.loader.exec_module(s41)
ROOT, OUT = s41.ROOT, s41.OUT
K = 0.5425

BOXES = {
    'rv': [(700, 310, 900, 440), (925, 300, 1145, 440), (1165, 285, 1405, 440)],
    'shop': [(725, 490, 870, 630), (940, 480, 1115, 630), (1175, 475, 1370, 640)],
    'home': [(700, 685, 885, 870), (925, 680, 1115, 870), (1175, 680, 1395, 870)],
}


def main():
    s = s41.Sheet('sheet36_home_foundations.jpg')
    entries = []
    for name, boxes in BOXES.items():
        for i, (x0, y0, x1, y1) in enumerate(boxes, 1):
            im = s.cutbox('o', x0 * K, y0 * K + 500, x1 * K, y1 * K + 500)
            bb = im.getchannel('A').point(lambda v: 255 if v > 8 else 0).getbbox()
            im = im.crop(bb)
            want = 230
            im = im.resize((want, max(1, round(im.height * want / im.width))), Image.LANCZOS)
            key = f'starter_{name}_{i}'
            im.save(os.path.join(OUT, key + '.png'), optimize=True)
            entries.append({'key': key, 'file': key + '.png', 'w': im.width, 'h': im.height, 'dw': 115})
    with open(os.path.join(ROOT, 'src', 'game', 'spriteListStarters.ts'), 'w') as f:
        f.write('// Generated by tools/slice_starters.py. Do not edit by hand.\n')
        f.write('export const STARTER_SPRITES = ' + json.dumps(entries, indent=2) + ' as const;\n')
    print(len(entries), [(e['key'], e['w'], e['h']) for e in entries])


if __name__ == '__main__':
    main()
