"""Cuts the floor tiles from sheets 36 and 37 into floor sprites the shop can sell.

Run:  python3 tools/slice_floors.py
Writes public/assets/sprites/floor_*.png, src/game/spriteListFloors.ts and src/game/floorOrigins.ts.
"""
import importlib.util, json, os
import numpy as np
from PIL import Image, ImageDraw, ImageFilter

HERE = os.path.dirname(os.path.abspath(__file__))
spec = importlib.util.spec_from_file_location('s41', os.path.join(HERE, 'slice_sheets41_45.py'))
s41 = importlib.util.module_from_spec(spec)
spec.loader.exec_module(s41)
ROOT, OUT = s41.ROOT, s41.OUT


def fy_of(im):
    """Where the middle of the top face sits, as a fraction of the sprite height (so thick slabs line up on the grid)."""
    a = np.array(im.getchannel('A')) > 60
    widths = a.sum(axis=1)
    rows = np.where(widths >= widths.max() * 0.97)[0]
    return float(rows.min() / im.height)  # the first widest row is where the left and right corners of the top face sit


def rhombus(sheet, box):
    x0, y0, x1, y1 = box
    im = sheet.img.crop((x0, y0, x1, y1)).convert('RGBA')
    big = im.resize((im.width * 4, im.height * 4), Image.LANCZOS)
    m = Image.new('L', big.size, 0)
    w, h = big.size
    inset = 10
    ImageDraw.Draw(m).polygon([(inset, h // 2), (w // 2, inset), (w - inset, h // 2), (w // 2, h - inset)], fill=255)
    big.putalpha(m.filter(ImageFilter.GaussianBlur(1.2)))
    return big.resize((im.width * 2, im.height * 2), Image.LANCZOS)


def main():
    s36 = s41.Sheet('sheet36_home_foundations.jpg')
    s37 = s41.Sheet('sheet37_modular_walls_floors.jpg')
    jobs = []
    for key, (x, y) in {'floor_pink_tile': (62, 357), 'floor_cafe_checker': (145, 357), 'floor_rug_blue': (228, 357), 'floor_rug_pink': (311, 357),
                        'floor_rug_yellow': (393, 357), 'floor_grass_flowers': (475, 357), 'floor_stone_path': (554, 357)}.items():
        c = s36.pt('o', x, y) if False else min([c for c in s36.cs if c[0] <= x <= c[2] and c[1] <= y <= c[3]], key=lambda c: (c[2] - c[0]) * (c[3] - c[1]))
        jobs.append((key, s36.cut(c)))
    for key, box in {'floor_wood_plank': (163, 66, 359, 180), 'floor_cream_stone': (386, 66, 580, 180), 'floor_mosaic': (611, 66, 808, 180), 'floor_terracotta': (835, 66, 1032, 180)}.items():
        jobs.append((key, s37.cutbox('o', *box)))
    for key, x0 in {'floor_wood_light': 655, 'floor_wood_mid': 740, 'floor_wood_dark': 824, 'floor_tatami': 909, 'floor_carpet_plush': 993}.items():
        jobs.append((key, rhombus(s36, (x0 + 1, 421, x0 + 72, 476))))
    entries, fys = [], {}
    for key, im in jobs:
        bb = im.getchannel('A').point(lambda v: 255 if v > 8 else 0).getbbox()
        im = im.crop(bb)
        want = 132
        im = im.resize((want, max(1, round(im.height * want / im.width))), Image.LANCZOS)
        im.save(os.path.join(OUT, key + '.png'), optimize=True)
        entries.append({'key': key, 'file': key + '.png', 'w': im.width, 'h': im.height, 'dw': 66})
        fys[key] = round(fy_of(im), 3)
    with open(os.path.join(ROOT, 'src', 'game', 'spriteListFloors.ts'), 'w') as f:
        f.write('// Generated by tools/slice_floors.py. Do not edit by hand.\n')
        f.write('export const FLOOR_SPRITES = ' + json.dumps(entries, indent=2) + ' as const;\n')
    with open(os.path.join(ROOT, 'src', 'game', 'floorOrigins.ts'), 'w') as f:
        f.write('// Generated by tools/slice_floors.py. Where the middle of each floor top sits in its sprite.\n')
        f.write('export const FLOOR_FY: Record<string, number> = ' + json.dumps(fys, indent=2) + ';\n')
    print(len(entries), fys)


if __name__ == '__main__':
    main()
