"""Cuts the painted island textures from art/source/sheet39 and sheet36: seasonal ground, dirt, sand and water.

The game maps these onto the island and the water, so they only need to look right, not tile on their own
(the renderer mirrors them at the edges). Run:  python3 tools/slice_env.py
Writes public/assets/sprites/env_*.png and src/game/spriteListEnv.ts.
"""
import json, os
import numpy as np
from PIL import Image, ImageFilter
from scipy import ndimage

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, 'art', 'source')
OUT = os.path.join(ROOT, 'public', 'assets', 'sprites')


def inpaint_lines(a, n=3):
    """Removes the pale grid lines drawn at the thirds of a ground square."""
    h, w, _ = a.shape
    a = a.astype(float)
    for axis in (1, 0):
        size = w if axis == 1 else h
        for k in (1, 2):
            c0 = round(size * k / n)
            lo, hi = max(1, c0 - 6), min(size - 2, c0 + 6)
            prof = a.mean(axis=(0, 2)) if axis == 1 else a.mean(axis=(1, 2))
            c = lo + int(np.argmax(prof[lo:hi]))
            for d in range(-3, 4):
                t = (d + 4) / 8
                if axis == 1:
                    a[:, c + d] = a[:, c - 4] * (1 - t) + a[:, c + 4] * t
                else:
                    a[c + d, :] = a[c - 4, :] * (1 - t) + a[c + 4, :] * t
    return np.clip(a, 0, 255).astype(np.uint8)


def main():
    os.makedirs(OUT, exist_ok=True)
    s39 = Image.open(os.path.join(SRC, 'sheet39_coastal_ground_water.jpg')).convert('RGB')
    s36 = Image.open(os.path.join(SRC, 'sheet36_home_foundations.jpg')).convert('RGB')
    entries = []

    def save(key, im, dw):
        im.save(os.path.join(OUT, key + '.png'), optimize=True)
        entries.append({'key': key, 'file': key + '.png', 'w': im.width, 'h': im.height, 'dw': dw})

    # seasonal ground: the four painted squares (spring, summer, autumn, winter)
    arr = np.array(s39).astype(int)
    lum = arr.mean(-1)
    mask = ndimage.binary_fill_holes(ndimage.binary_closing(lum < 110, iterations=3))
    lab, n = ndimage.label(mask)
    boxes = []
    for i, sl in enumerate(ndimage.find_objects(lab)):
        h, w = sl[0].stop - sl[0].start, sl[1].stop - sl[1].start
        if 200 < w < 290 and 200 < h < 290 and sl[0].start < 200:
            boxes.append((sl[1].start, sl[0].start, sl[1].stop, sl[0].stop))
    boxes.sort()
    assert len(boxes) == 4, boxes
    for name, (x0, y0, x1, y1) in zip(['spring', 'summer', 'autumn', 'winter'], boxes):
        sq = np.array(s39.crop((x0 + 6, y0 + 6, x1 - 6, y1 - 6)))
        sq = inpaint_lines(sq)
        im = Image.fromarray(sq).resize((256, 256), Image.LANCZOS).filter(ImageFilter.GaussianBlur(0.5))
        save(f'env_ground_{name}', im, 128)

    # blank dirt: sample the colour of the starter slab and paint soft earthy patches around it
    top = np.array(s36.crop((930, 112, 1020, 140))).reshape(-1, 3)
    base = np.median(top, axis=0)
    rng = np.random.default_rng(7)
    h = w = 256
    field = np.zeros((h, w))
    for scale, amp in [(40, 0.5), (14, 0.3), (5, 0.2)]:
        noise = ndimage.zoom(rng.random((h // scale + 2, w // scale + 2)), scale, order=3)[:h, :w]
        field += (noise - 0.5) * amp
    img = np.clip(base[None, None, :] * (1 + field[..., None] * 0.55), 0, 255)
    specks = rng.random((h, w)) > 0.992
    img[ndimage.binary_dilation(specks)] *= 0.86
    save('env_ground_dirt', Image.fromarray(img.astype(np.uint8)).filter(ImageFilter.GaussianBlur(0.8)), 128)

    # sand from the painted shoreline pieces
    sand = s39.crop((133, 768, 200, 805)).resize((237, 131), Image.LANCZOS).filter(ImageFilter.GaussianBlur(0.8))
    save('env_sand', sand, 118)

    # water: the middle of each painted water circle
    for name, cx in zip(['spring', 'summer', 'autumn', 'winter'], [523, 679, 836, 993]):
        cy, r = 586, 47
        w = s39.crop((cx - r, cy - r, cx + r, cy + r)).resize((188, 188), Image.LANCZOS)
        save(f'env_water_{name}', w, 94)

    with open(os.path.join(ROOT, 'src', 'game', 'spriteListEnv.ts'), 'w') as f:
        f.write('// Generated by tools/slice_env.py. Do not edit by hand.\n')
        f.write('export const ENV_SPRITES = ' + json.dumps(entries, indent=2) + ' as const;\n')
    print('wrote', len(entries))


if __name__ == '__main__':
    main()
