"""Cuts the original starting path art (sheet 57) cleanly, as rounded cards:
 * path_card_<path>   the tinted card with the icon (RV, Shop and Cafe, Home Foundation)
 * path_scene_<path>  the big island picture for each path, used by the "See on Island" view
 * path_<path>_1..4   the four Build Up Over Time stages
Run:  python3 tools/slice_paths.py   Writes public/assets/sprites/path_*.png and src/game/spriteListPaths.ts
"""
import importlib.util, json, os
import numpy as np
from PIL import Image, ImageDraw, ImageFilter

HERE = os.path.dirname(os.path.abspath(__file__))
spec = importlib.util.spec_from_file_location('s41', os.path.join(HERE, 'slice_sheets41_45.py'))
s41 = importlib.util.module_from_spec(spec)
spec.loader.exec_module(s41)
ROOT, OUT = s41.ROOT, s41.OUT

CARDS = {'rv': (850, 129, 976, 226), 'shop': (1000, 122, 1132, 225), 'home': (1154, 120, 1281, 225)}
SCENES = {'rv': (24, 433, 427, 694), 'shop': (453, 436, 858, 694), 'home': (884, 436, 1289, 694)}


def strip(x0, y0, x1, y1):
    return (20 + x0 * 0.64, 930 + y0 * 0.64, 20 + x1 * 0.64, 930 + y1 * 0.64)


STAGES = {
    'rv': [strip(30, 55, 110, 125), strip(150, 50, 290, 130), strip(325, 50, 450, 130), strip(480, 55, 610, 125)],
    'shop': [strip(705, 55, 795, 125), strip(855, 50, 955, 130), strip(1020, 55, 1105, 125), strip(1170, 55, 1270, 125)],
    'home': [strip(1380, 55, 1470, 125), strip(1535, 55, 1625, 125), strip(1690, 55, 1775, 125), strip(1840, 45, 1950, 125)],
}


def rounded(img, box, radius, scale):
    """A clean rounded rectangle crop, upscaled so the corners are smooth, with the very edge trimmed to avoid a pale fringe."""
    x0, y0, x1, y1 = box
    crop = img.crop((x0 + 1, y0 + 1, x1 - 1, y1 - 1))
    big = crop.resize((crop.width * scale, crop.height * scale), Image.LANCZOS).filter(ImageFilter.UnsharpMask(1.1, 60, 2)).convert('RGBA')
    m = Image.new('L', big.size, 0)
    ImageDraw.Draw(m).rounded_rectangle([0, 0, big.width - 1, big.height - 1], radius=radius * scale, fill=255)
    big.putalpha(m)
    return big


def main():
    img = Image.open(os.path.join(s41.SRC, 'sheet57_original_start_paths.webp')).convert('RGB')
    sh = s41.Sheet('sheet36_home_foundations.jpg')
    sh.img = img
    entries = []

    def save(key, im, dw):
        im.save(os.path.join(OUT, key + '.png'), optimize=True)
        entries.append({'key': key, 'file': key + '.png', 'w': im.width, 'h': im.height, 'dw': dw})

    for k, b in CARDS.items():
        save(f'path_card_{k}', rounded(img, b, 9, 3), 70)
    for k, b in SCENES.items():
        save(f'path_scene_{k}', rounded(img, b, 8, 2), 200)
    for k, boxes in STAGES.items():
        for i, b in enumerate(boxes, 1):
            im = sh.cutbox('o', *b, keep_all=True)
            bb = im.getchannel('A').point(lambda v: 255 if v > 8 else 0).getbbox()
            if bb:
                im = im.crop(bb)
            im = im.resize((im.width * 3, im.height * 3), Image.LANCZOS).filter(ImageFilter.UnsharpMask(1.2, 80, 2))
            save(f'path_{k}_{i}', im, 62)
    # the day one structure on the island: the building cut out of your path card
    for k, b in CARDS.items():
        im = sh.cutbox('o', b[0] + 3, b[1] + 3, b[2] - 3, b[3] - 3)
        bb = im.getchannel('A').point(lambda v: 255 if v > 8 else 0).getbbox()
        if bb:
            im = im.crop(bb)
        w = 230
        im = im.resize((w, round(im.height * w / im.width)), Image.LANCZOS).filter(ImageFilter.UnsharpMask(1.0, 50, 2))
        save(f'starter_day1_{k}', im, 115)
    with open(os.path.join(ROOT, 'src', 'game', 'spriteListPaths.ts'), 'w') as f:
        f.write('// Generated by tools/slice_paths.py. Do not edit by hand.\n')
        f.write('export const PATH_SPRITES = ' + json.dumps(entries, indent=2) + ' as const;\n')
    print([(e['key'], e['w'], e['h']) for e in entries if 'card' in e['key'] or 'scene' in e['key']])


if __name__ == '__main__':
    main()
