"""Cuts the detailed starting path art (sheet 59): the RV, the Shop and Cafe, the Home Foundation, and their props.
The characters on the sheet are ignored. Run:  python3 tools/slice_starters2.py
Writes public/assets/sprites/start_*.png, the path cards, and src/game/spriteListStart.ts
"""
import importlib.util, json, os
from PIL import Image, ImageDraw, ImageFilter

HERE = os.path.dirname(os.path.abspath(__file__))
spec = importlib.util.spec_from_file_location('s41', os.path.join(HERE, 'slice_sheets41_45.py'))
s41 = importlib.util.module_from_spec(spec)
spec.loader.exec_module(s41)
ROOT, OUT = s41.ROOT, s41.OUT

B = {  # key: (box, display width in game px)
    'rv': ((50, 373, 323, 566), 140), 'shop': ((409, 368, 676, 585), 130), 'home': ((762, 370, 1050, 574), 140),
    'packs': ((22, 563, 172, 713), 44), 'duffel': ((196, 586, 338, 716), 44), 'toolbox_rv': ((31, 753, 141, 871), 34),
    'campfire': ((180, 757, 292, 860), 40), 'stool_a': ((149, 750, 199, 807), 16), 'stool_b': ((272, 750, 323, 807), 16), 'stool_c': ((292, 814, 343, 872), 16),
    'cafe_table': ((389, 640, 542, 732), 46), 'cafe_umbrella': ((565, 576, 702, 734), 46), 'cafe_shelf': ((404, 748, 519, 872), 36), 'menu_board': ((592, 745, 685, 870), 30),
    'lumber': ((745, 591, 914, 725), 54), 'frames': ((937, 573, 1064, 732), 40), 'wall_unit': ((747, 744, 923, 865), 54), 'toolbox_home': ((957, 760, 1061, 866), 32),
}


def main():
    s = s41.Sheet('sheet59_starter_detailed.jpg')
    entries, imgs = [], {}
    for k, (b, dw) in B.items():
        im = s.cutbox('o', *b)
        bb = im.getchannel('A').point(lambda v: 255 if v > 8 else 0).getbbox()
        if bb:
            im = im.crop(bb)
        want = max(dw * 2, 60)
        if im.width != want:
            im = im.resize((want, max(1, round(im.height * want / im.width))), Image.LANCZOS)
        im = im.filter(ImageFilter.UnsharpMask(0.8, 40, 2))
        key = f'start_{k}'
        im.save(os.path.join(OUT, key + '.png'), optimize=True)
        entries.append({'key': key, 'file': key + '.png', 'w': im.width, 'h': im.height, 'dw': dw})
        imgs[k] = im
    # the path cards: the new building on the same tinted panels as the original cards
    tints = {'rv': (207, 238, 230), 'shop': (253, 226, 200), 'home': (252, 220, 228)}
    for k, col in tints.items():
        W, H = 420, 372
        card = Image.new('RGBA', (W, H), col + (255,))
        d = ImageDraw.Draw(card)
        # a soft lighter wash so the panel is not flat
        wash = Image.new('RGBA', (W, H), (255, 255, 255, 0))
        ImageDraw.Draw(wash).ellipse([40, 60, W - 40, H + 120], fill=(255, 255, 255, 70))
        card.alpha_composite(wash.filter(ImageFilter.GaussianBlur(30)))
        b = imgs[k].copy()
        sc = min((W - 60) / b.width, (H - 50) / b.height)
        b = b.resize((round(b.width * sc), round(b.height * sc)), Image.LANCZOS)
        card.alpha_composite(b, ((W - b.width) // 2, (H - b.height) // 2 + 6))
        m = Image.new('L', (W, H), 0)
        ImageDraw.Draw(m).rounded_rectangle([0, 0, W - 1, H - 1], radius=28, fill=255)
        card.putalpha(m)
        card.save(os.path.join(OUT, f'path_card_{k}.png'), optimize=True)
    with open(os.path.join(ROOT, 'src', 'game', 'spriteListStart.ts'), 'w') as f:
        f.write('// Generated by tools/slice_starters2.py. Do not edit by hand.\n')
        f.write('export const START_SPRITES = ' + json.dumps(entries, indent=2) + ' as const;\n')
    print({e['key']: (e['w'], e['h']) for e in entries})


if __name__ == '__main__':
    main()
