"""Cuts the original starting path art (sheet 57): the three path card icons and the four build up stages of each path.
Run:  python3 tools/slice_paths.py   Writes public/assets/sprites/path_*.png and src/game/spriteListPaths.ts
"""
import importlib.util, json, os
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
spec = importlib.util.spec_from_file_location('s41', os.path.join(HERE, 'slice_sheets41_45.py'))
s41 = importlib.util.module_from_spec(spec)
spec.loader.exec_module(s41)
ROOT, OUT = s41.ROOT, s41.OUT

def strip(x0, y0, x1, y1):  # coordinates of the 2000 px wide view of the strip crop (20, 930) at 2x
    return (20 + x0 * 0.64, 930 + y0 * 0.64, 20 + x1 * 0.64, 930 + y1 * 0.64)

CARDS = {'rv': (848, 148, 985, 238), 'shop': (995, 118, 1135, 238), 'home': (1150, 150, 1285, 238)}
STAGES = {
    'rv': [strip(30, 55, 110, 125), strip(150, 50, 290, 130), strip(325, 50, 450, 130), strip(480, 55, 610, 125)],
    'shop': [strip(705, 55, 795, 125), strip(855, 50, 955, 130), strip(1020, 55, 1105, 125), strip(1170, 55, 1270, 125)],
    'home': [strip(1380, 55, 1470, 125), strip(1535, 55, 1625, 125), strip(1690, 55, 1775, 125), strip(1840, 45, 1950, 125)],
}

def main():
    from PIL import ImageFilter
    img = Image.open(os.path.join(s41.SRC, 'sheet57_original_start_paths.webp')).convert('RGB')
    # a 4x smooth upscale makes the small icons cleaner to cut and to display
    class S: pass
    sh = s41.Sheet('sheet36_home_foundations.jpg')  # only used for its cutbox method
    sh.img = img
    entries = []
    def save(key, im, dw, up=1):
        bb = im.getchannel('A').point(lambda v: 255 if v > 8 else 0).getbbox()
        if bb: im = im.crop(bb)
        if up > 1:
            im = im.resize((im.width * up, im.height * up), Image.LANCZOS).filter(ImageFilter.UnsharpMask(1.2, 80, 2))
        im.save(os.path.join(OUT, key + '.png'), optimize=True)
        entries.append({'key': key, 'file': key + '.png', 'w': im.width, 'h': im.height, 'dw': dw})
    for k, b in CARDS.items():
        save(f'path_card_{k}', sh.cutbox('o', *b), 70)
    for k, boxes in STAGES.items():
        for i, b in enumerate(boxes, 1):
            save(f'path_{k}_{i}', sh.cutbox('o', *b, keep_all=True), 62, up=3)
    with open(os.path.join(ROOT, 'src', 'game', 'spriteListPaths.ts'), 'w') as f:
        f.write('// Generated by tools/slice_paths.py. Do not edit by hand.\n')
        f.write('export const PATH_SPRITES = ' + json.dumps(entries, indent=2) + ' as const;\n')
    print([(e['key'], e['w'], e['h']) for e in entries])

if __name__ == '__main__':
    main()
