"""Cuts the town buildings and plaza props from sheets 51, 52 and 54.
Boxes are in sheet pixels (the sheets are 1085 x 992). Run:  python3 tools/slice_town.py
Writes public/assets/sprites/town_*.png and src/game/spriteListTown.ts
"""
import importlib.util, json, os
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
spec = importlib.util.spec_from_file_location('s41', os.path.join(HERE, 'slice_sheets41_45.py'))
s41 = importlib.util.module_from_spec(spec)
spec.loader.exec_module(s41)
ROOT, OUT = s41.ROOT, s41.OUT

# sheet 54: crop shown at 3x from (540, 95)
def b54(x0, y0, x1, y1):
    return (540 + x0 / 3, 95 + y0 / 3, 540 + x1 / 3, 95 + y1 / 3)

BUILD = {
    'school': b54(40, 80, 420, 400), 'library': b54(430, 60, 800, 380), 'station': b54(810, 85, 1225, 370), 'hall': b54(1230, 50, 1600, 400),
    'hospital': b54(30, 520, 400, 850), 'fire': b54(435, 520, 800, 850), 'bakery': b54(840, 520, 1190, 850), 'bank': b54(1230, 520, 1600, 850),
    'cinema': b54(30, 975, 390, 1300), 'gym': b54(435, 975, 800, 1300), 'yoga': b54(840, 975, 1190, 1300), 'petshop': b54(1235, 970, 1600, 1300),
    'pavilion': b54(60, 1415, 380, 1700), 'arcade': b54(455, 1405, 780, 1700), 'stage': b54(850, 1440, 1130, 1700), 'stalls': b54(1160, 1440, 1600, 1690),
}
BUILD_DW = {'school': 160, 'library': 130, 'station': 160, 'hall': 160, 'hospital': 130, 'fire': 130, 'bakery': 130, 'bank': 130, 'cinema': 130, 'gym': 130,
            'yoga': 130, 'petshop': 130, 'pavilion': 128, 'arcade': 130, 'stage': 128, 'stalls': 130}
P51 = {
    'bulletin_1': (22, 145, 125, 235), 'bulletin_2': (132, 145, 235, 235), 'bulletin_3': (292, 145, 392, 235), 'bulletin_4': (398, 145, 500, 235),
    'well_2': (128, 300, 222, 385), 'well_3': (228, 300, 325, 385),
    'icecream_1': (330, 305, 420, 390),
    'pigeons_idle': (22, 490, 128, 545), 'pigeons_scatter': (130, 490, 225, 545), 
    'trash_1': (560, 150, 665, 235), 'trash_2': (682, 150, 780, 235), 'drink_1': (560, 305, 665, 385), 'drink_2': (685, 305, 785, 385),
    'news_1': (825, 150, 925, 235), 'news_2': (948, 150, 1050, 235),
    'ov_leaves': (110, 785, 195, 850), 
}
P52 = {
    'fountain_dry': (478, 815, 578, 893), 'fountain_flow': (598, 818, 700, 893), 'fountain_fest': (720, 815, 820, 893),
    'bench_straight': (575, 170, 670, 240), 'bench_curved': (685, 160, 810, 240), 'flowerbed': (690, 305, 815, 390), 'planter': (830, 305, 950, 395),
    'clock': (595, 455, 650, 560), 'stall_fruit': (20, 625, 100, 735), 'stall_crafts': (118, 625, 205, 735), 'stall_bakery': (225, 625, 310, 735),
}


def main():
    s54 = s41.Sheet('sheet54_town_part8.jpg')
    s51 = s41.Sheet('sheet51_plaza_expansion.jpg')
    s52 = s41.Sheet('sheet52_town_square_package.jpg')
    jobs = []
    for k, b in BUILD.items():
        jobs.append((f'town_{k}', s54.cutbox('o', *b), BUILD_DW[k]))
    for k, b in P51.items():
        jobs.append((f'town_{k}', s51.cutbox('o', *b), 22 if k.startswith('pigeons') else 50 if k.startswith(('bulletin', 'icecream')) else 40))
    for k, b in P52.items():
        jobs.append((f'town_{k}', s52.cutbox('o', *b), 26 if k == 'clock' else 40 if k in ('fountain_dry', 'bench_straight') else 56))
    entries = []
    for key, im, dw in jobs:
        bb = im.getchannel('A').point(lambda v: 255 if v > 8 else 0).getbbox()
        if bb:
            im = im.crop(bb)
        want = dw * 2
        if im.width > want:
            im = im.resize((want, max(1, round(im.height * want / im.width))), Image.LANCZOS)
        im.save(os.path.join(OUT, key + '.png'), optimize=True)
        entries.append({'key': key, 'file': key + '.png', 'w': im.width, 'h': im.height, 'dw': dw})
    with open(os.path.join(ROOT, 'src', 'game', 'spriteListTown.ts'), 'w') as f:
        f.write('// Generated by tools/slice_town.py. Do not edit by hand.\n')
        f.write('export const TOWN_SPRITES = ' + json.dumps(entries, indent=2) + ' as const;\n')
    print(len(entries))


if __name__ == '__main__':
    main()
